### ISSUE TITLE
Platform: Gitlab, Manager: Kustomize, Datasource: gitlab-tags, remote kustomize base and hostRules auth ?

### ISSUE THREAD

**Issue by lukasmrtvy** [renovatebot/config-help#1013]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?
I am not sure, how to setup Kustomize with gitlab-tabs for remote bases as packageRule with hostRules auth support.
Do I need to use hostRules ? Or gitlab-tags are fetched via Renovate user and RENOVATE_TOKEN via API ? Thanks

https://gitlab.example.com/engineering/environments/ondemand/renovate.json
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "prHourlyLimit": 60,
  "prConcurrentLimit": 5,
  "packageRules": [{
      "managers": ["kustomize"],
      "datasources": ["gitlab-tags"],
      "registryUrls": ["https://gitlab.example.com/"]
  }]
}
```
config.js
```
module.exports = {
    platform: 'gitlab',
    endpoint: 'https://gitlab.example.com/api/v4/',
    token: process.env.RENOVATE_TOKEN,
    repositories: [
        'engineering/environments/ondemand'
    ],
    hostRules: [{
      baseUrl: "https://gitlab.example.com/engineering/cd/k8s/kustomize",
      username: process.env.GROUP_RO_USERNAME,
      password: process.env.GROUP_RO_PASSWORD,
      enabled: true
    }],
};
```
https://gitlab.example.com/engineering/environments/ondemand/kustomization.yaml
```
kind: Kustomization

resources:
- https://gitlab.example.com/engineering/cd/k8s/kustomize/podinfo.git?ref=1.0.1

```

https://gitlab.example.com/engineering/cd/k8s/kustomize/podinfo/kustomization.yaml
```
kind: Kustomization

resources:
- deployment.yaml
```

**Comment by lukasmrtvy** [comment]
I belive it must be a bug in kustomize:

```
DEBUG: Found kustomize package files (repository=engineering/environments/ondemand)
DEBUG: Found 1 package file(s) (repository=engineering/environments/ondemand)
 INFO: Dependency extraction complete (repository=engineering/environments/ondemand)
       "baseBranch": "master",
       "stats": {
         "managers": {"kustomize": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
DEBUG: baseBranch: master (repository=engineering/environments/ondemand)
DEBUG: Datasource unknown error (repository=engineering/environments/ondemand)
       "datasource": "git-tags",
       "lookupName": "https://gitlab.example.com/engineering/cd",
       "err": {
         "task": {
           "commands": ["ls-remote", "https://gitlab.example.com/engineering/cd"],
           "format": "utf-8"
         },
         "message": "fatal: could not read Username for 'https://gitlab.example.com': No such device or address\n",
         "stack": "Error: fatal: could not read Username for 'https://gitlab.example.com': No such device or address\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:66:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:58:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
DEBUG: Failed to look up dependency gitlab.example.com/engineering/cd (repository=engineering/environments/ondemand, packageFile=kustomization.yaml, dependency=gitlab.example.com/engineering/cd)
DEBUG: Package releases lookups complete (repository=engineering/environments/ondemand)
       "baseBranch": "master"
DEBUG: packageFiles with updates (repository=engineering/environments/ondemand)
       "config": {
         "kustomize": [
           {
             "packageFile": "kustomization.yaml",
             "manager": "kustomize",
             "deps": [
               {
                 "datasource": "git-tags",
                 "depName": "gitlab.example.com/engineering/cd",
                 "depNameShort": "engineering/cd",
                 "lookupName": "https://gitlab.example.com/engineering/cd",
                 "currentValue": "1.0.1",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "depName": "gitlab.example.com/engineering/cd",
                     "message": "Failed to look up dependency gitlab.example.com/engineering/cd"
                   }
                 ],
                 "fixedVersion": "1.0.1"
               }
             ]
           }
         ]
       }
```

Its trying to do "lookupName": "https://gitlab.example.com/engineering/cd" , but actual kustomize base is located in nested group https://gitlab.example.com/engineering/cd/k8s/kustomize/podinfo

**Comment by viceice** [comment]
@lukasmrtvy https://github.com/renovatebot/renovate/issues/7783 is a duplicate of https://github.com/renovatebot/renovate/issues/5471

**Comment by viceice** [comment]
This also needs renovatebot/renovate#7877, that way renovate can properly detect the gitlab urls

**Comment by viceice** [comment]
As workaround can you try the following regex manager?

```json
{
  "regexManagers": [
    {
      "fileMatch": ["(^|/)kustomization\\.yaml$"],
      "matchStrings": ["\\s- (?<registryUrl>https:\\/\\/[^/]+)\\/(?<depName>.+)\\.git\\?ref=(?<currentValue>.*?)\s"],
      "datasourceTemplate": "gitlab-tags"
    }
  ]
}
```

**Comment by lukasmrtvy** [comment]
@viceice 
Still getting:
```
DEBUG: Datasource unknown error (repository=engineering/environments/ondemand)
       "datasource": "git-tags",
       "lookupName": "https://gitlab.example.com/engineering/cd",
       "err": {
         "task": {
           "commands": ["ls-remote", "https://gitlab.example.com/engineering/cd"],
           "format": "utf-8"
         },
         "message": "fatal: could not read Username for 'https://gitlab.example.com': No such device or address\n",
         "stack": "Error: fatal: could not read Username for 'https://gitlab.example.com': No such device or address\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:66:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:58:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
```

**Comment by viceice** [comment]
You would need a package rule to disable the default git-tags behavior for that package, then renovate won't try to lookup.
