### ISSUE TITLE
Problem with pipsetup pipfile 

### ISSUE THREAD

**Issue by Hartorn** [renovatebot/config-help#150]
### Which Renovate are you using? 
App, with docker image in Kubernetes

### Which platform are you using?
Gitlab

### Have you checked the logs? Don't forget to include them if relevant
Cf stacktrace in next message

### What is your question?

I'm trying with docker to run renovate on some repo with python dependencies
I put 
```
   "pipenv": {
        "enabled": true
    },
    "pip_setup": {
        "enabled": true
    },
```
 inside renovate.json.

It seems to fail at runtime, because it does not find python (cf stack in next message)
@rarkins Should I use another image instead of renovate/renovate ? 

Edit: reformat using template

**Comment by Hartorn** [comment]
To be a bit more precise
```
   "pipenv": {
        "enabled": true
    },
    "pip_setup": {
        "enabled": true
    },
```
is added inside renovate.json.

Here is the error 
```
2019-01-30T12:56:20.3399697Z  INFO: Running python via global command (repository=<repository>)
2019-01-30T12:56:20.348916124Z  WARN: Failed to read setup file (repository=<repository>)
2019-01-30T12:56:20.348942407Z        "err": {
2019-01-30T12:56:20.348945758Z          "name": "ChildProcessError",
2019-01-30T12:56:20.348948925Z          "code": 127,
2019-01-30T12:56:20.348951824Z          "childProcess": {},
2019-01-30T12:56:20.348954737Z          "stdout": "",
2019-01-30T12:56:20.348957699Z          "stderr": "/bin/sh: 1: python: not found\n",
2019-01-30T12:56:20.348961066Z          "message": "Command failed: python /usr/src/app/lib/manager/pip_setup/extract.py api-template/setup.py\n/bin/sh: 1: python: not found\n `python /usr/src/app/lib/manager/pip_setup/extract.py api-template/setup.py` (exited with error code 127)",
2019-01-30T12:56:20.348964786Z          "stack": "ChildProcessError: Command failed: python /usr/src/app/lib/manager/pip_setup/extract.py api-template/setup.py\n/bin/sh: 1: python: not found\n `python /usr/src/app/lib/manager/pip_setup/extract.py api-template/setup.py` (exited with error code 127)\n    at callback (/usr/src/app/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:182:13)\n    at maybeClose (internal/child_process.js:962:16)\n    at Socket.stream.socket.on (internal/child_process.js:381:11)\n    at Socket.emit (events.js:182:13)\n    at Pipe._handle.close (net.js:610:12)"
2019-01-30T12:56:20.348970991Z        }
2019-01-30T12:56:20.356729836Z  INFO: Running python via global command (repository=<repository>)
2019-01-30T12:56:20.363146942Z  WARN: Failed to read setup file (repository=<repository>)
2019-01-30T12:56:20.36317752Z        "err": {
2019-01-30T12:56:20.363192352Z          "name": "ChildProcessError",
2019-01-30T12:56:20.363195638Z          "code": 127,
2019-01-30T12:56:20.363198727Z          "childProcess": {},
2019-01-30T12:56:20.363201359Z          "stdout": "",
2019-01-30T12:56:20.363204136Z          "stderr": "/bin/sh: 1: python: not found\n",
2019-01-30T12:56:20.363207062Z          "message": "Command failed: python /usr/src/app/lib/manager/pip_setup/extract.py setup.py\n/bin/sh: 1: python: not found\n `python /usr/src/app/lib/manager/pip_setup/extract.py setup.py` (exited with error code 127)",
2019-01-30T12:56:20.363210706Z          "stack": "ChildProcessError: Command failed: python /usr/src/app/lib/manager/pip_setup/extract.py setup.py\n/bin/sh: 1: python: not found\n `python /usr/src/app/lib/manager/pip_setup/extract.py setup.py` (exited with error code 127)\n    at callback (/usr/src/app/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:182:13)\n    at maybeClose (internal/child_process.js:962:16)\n    at Socket.stream.socket.on (internal/child_process.js:381:11)\n    at Socket.emit (events.js:182:13)\n    at Pipe._handle.close (net.js:610:12)"
2019-01-30T12:56:20.363215993Z        }
2019-01-30T12:56:20.408245307Z ERROR: Repository has unknown error (repository=<repository>)
2019-01-30T12:56:20.408277466Z        "err": {
2019-01-30T12:56:20.408281225Z          "message": "Cannot convert object to primitive value",
2019-01-30T12:56:20.408284529Z          "stack": "TypeError: Cannot convert object to primitive value\n    at RegExp.exec (<anonymous>)\n    at Object.entries.map.x (/usr/src/app/lib/manager/pipenv/extract.js:61:47)\n    at Array.map (<anonymous>)\n    at extractFromSection (/usr/src/app/lib/manager/pipenv/extract.js:49:6)\n    at Object.extractPackageFile (/usr/src/app/lib/manager/pipenv/extract.js:34:8)\n    at module.exports.(anonymous function).params (/usr/src/app/lib/manager/index.js:64:34)\n    at getManagerPackageFiles (/usr/src/app/lib/workers/repository/extract/manager-files.js:54:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-01-30T12:56:20.408291161Z        }
2019-01-30T12:56:20.408293787Z  INFO: Unknown error (repository=<repository>)
2019-01-30T12:56:20.408296781Z        "err": {
2019-01-30T12:56:20.408299478Z          "message": "Cannot convert object to primitive value",
2019-01-30T12:56:20.408302451Z          "stack": "TypeError: Cannot convert object to primitive value\n    at RegExp.exec (<anonymous>)\n    at Object.entries.map.x (/usr/src/app/lib/manager/pipenv/extract.js:61:47)\n    at Array.map (<anonymous>)\n    at extractFromSection (/usr/src/app/lib/manager/pipenv/extract.js:49:6)\n    at Object.extractPackageFile (/usr/src/app/lib/manager/pipenv/extract.js:34:8)\n    at module.exports.(anonymous function).params (/usr/src/app/lib/manager/index.js:64:34)\n    at getManagerPackageFiles (/usr/src/app/lib/workers/repository/extract/manager-files.js:54:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-01-30T12:56:20.408307394Z        },
2019-01-30T12:56:20.408309978Z        "message": "Cannot convert object to primitive value"
```

**Comment by rarkins** [comment]
It looks like we need to add the necessary binaries (python, pipenv) to the Dockerfile in the Renovate repo so that they get built in. Nothing wrong with your config so closing here

**Comment by rarkins** [comment]
Please check it Issues #3152 and #3153 in the main Renovate repo. Either would be a solution for you
