### ISSUE TITLE
[Question] maven configuration with multiple urls and authentication

### ISSUE THREAD

**Issue by 123Haynes** [renovatebot/config-help#178]
### Which Renovate are you using? CLI, App, or Pro
CLI (official docker image)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Gitlab

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Parsing configs
DEBUG: No config file found on disk - skipping
```

### What is your question?

I'm trying to use the docker image with gitlab-ci.
I execute it with the following command:
`docker run -e LOG_LEVEL="DEBUG" -e HTTP_PROXY="$HTTP_PROXY" -e HTTPS_PROXY="$HTTPS_PROXY" -e http_proxy="$HTTP_PROXY" -e https_proxy="$HTTPS_PROXY" -e RENOVATE_TOKEN="$RENOVATE_TOKEN" -e GITHUB_COM_TOKEN="$GITHUB_COM_TOKEN" -v $PWD/config.js:/usr/src/app/config.js renovate/renovate:latest $(cat repositories.txt | xargs)`

The config.js lloks like this:
```
module.exports = {
	platform: 'gitlab',
	endpoint: 'https://private_gitlab/api/v4/',
	assignees: ['myself'],
	baseBranches: ['master'],
	labels: ['renovate'],
	logLevel: 'info',
	extends: ['config:base']
};
```

I followed the instructions from #162 , but renovate tries to use github as a platform because it doesn't read my config.
What am I missing here?

**Comment by rarkins** [comment]
I'm not sure what's going wrong for you, but I tested something similar and it works fine just now. 

FYI I recommend against embedding `extends: ['config:base']` into your bot config. It's better as `onboardingConfig: { extends: ['config:base'] }`. 


```
$ docker run -e LOG_LEVEL="debug" -e RENOVATE_TOKEN="$RENOVATE_TOKEN" -e GITHUB_COM_TOKEN="$GITHUB_COM_TOKEN" -v $PWD/config.js:/usr/src/app/config.js renovate/renovate:latest --autodiscover=true
DEBUG: Parsing configs
DEBUG: File config
       "config": {
         "platform": "gitlab",
         "endpoint": "https://gitlab.com/api/v4/",
         "assignees": ["renovate-tests"],
         "labels": ["renovate"],
         "logLevel": "info"
       }
DEBUG: CLI config
       "config": {"autodiscover": true}
DEBUG: Env config
       "config": {
         "hostRules": [
           {
             "endpoint": "https://api.github.com/",
             "platform": "github",
             "token": "***********"
           }
         ],
         "logLevel": "debug",
         "token": "***********"
       }
DEBUG: Combined config
       "config": {
         "platform": "gitlab",
         "endpoint": "https://gitlab.com/api/v4/",
         "assignees": ["renovate-tests"],
         "labels": ["renovate"],
         "logLevel": "debug",
         "hostRules": [
           {
             "endpoint": "https://api.github.com/",
             "platform": "github",
             "token": "***********"
           }
         ],
         "token": "***********",
         "autodiscover": true
       }
```

**Comment by 123Haynes** [comment]
@rarkins Thanks for the info :+1:   
It looks like one of my runners is misconfigured somehow. The command works fine when another runner executes it.  
Now I'm only battling against our corporate proxy.
Is it possible to disable the check for docker dependencies in the config.js? 
I don't really need it right now, but currently our proxy 503s the requests to index.docker.io for some reason and it keeps me from setting up a test project with the bot.

**Comment by rarkins** [comment]
Quickest way to disable all docker is:

```
  "docker": { "enabled": false }
```

**Comment by 123Haynes** [comment]
@rarkins Thank you so much! :+1:   Thanks to you I was able to setup the bot for one of my repos :smile: 
One (hopefully last) question:

I'm trying to add our internal artifactory as a source for maven so renovate also detects when a private lib gets updated:
I saw that this should be possible with registryUrls and hostRules, but I can't figure out where to place those directives in the config.
Also what would the syntax look like if I want to add different credentials for more than one platform? i.e. docker and maven. I only found an example with one credential pair.

Currently my non working config looks like this:
```
module.exports = {
	platform: 'gitlab',
	endpoint: 'https://private_gitlab/api/v4/',
	labels: ['renovate'],
	logLevel: 'info',
	docker: {"enabled": false },
	maven: {
	    "enabled": true,
	    "registryUrls": ["https://artifactoryurl1/", "https://artifactoryurl2/"]
	},
	hostRules: {
	    "platform": "maven",
	    "username": "artifactoryusername",
	    "password": "artifactorypassword"
	},
	onboardingConfig: { extends: ["config:base"] }
};

```

**Comment by rarkins** [comment]
Authenticated Maven is not yet supported but will be soon.

**Comment by 123Haynes** [comment]
awesome! Thank you :)

**Comment by rarkins** [comment]
@123Haynes 	Maven authentication is now supported in renovate@14.42.0

Could you test it out and let me know how you go?

**Comment by 123Haynes** [comment]
@rarkins sure. If you can help me with the correct config.

with the last config i posted i get these errors:
```
FATAL: Fatal error: (parentConfig[option.name] || []).concat is not a function
       "err": {
         "message": "(parentConfig[option.name] || []).concat is not a function",
         "stack": "TypeError: (parentConfig[option.name] || []).concat is not a function\n    at mergeChildConfig (/usr/src/app/lib/config/index.js:155:65)\n    at Object.parseConfigs (/usr/src/app/lib/config/index.js:44:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)"
       }
```

**Comment by rarkins** [comment]
There was a documentation typo you may have seen before. Please try this:

```
module.exports = {
	platform: 'gitlab',
	endpoint: 'https://private_gitlab/api/v4/',
	labels: ['renovate'],
	logLevel: 'info',
	docker: {"enabled": false },
	maven: {
	    "enabled": true,
	    "registryUrls": ["https://artifactoryurl1/", "https://artifactoryurl2/"]
	},
	hostRules: [{
	    "platform": "maven",
	    "username": "artifactoryusername",
	    "password": "artifactorypassword"
	}],
	onboardingConfig: { extends: ["config:base"] }
};

```

i.e. hostRules must be an Array

**Comment by 123Haynes** [comment]
@rarkins ok. Now i have a different error message:  
```
FATAL: Fatal error: Failed to configure platform 'maven': no endpoint defined
       "err": {
         "message": "Failed to configure platform 'maven': no endpoint defined",
         "stack": "Error: Failed to configure platform 'maven': no endpoint defined\n    at update (/usr/src/app/lib/util/host-rules.js:42:11)\n    at Array.forEach (<anonymous>)\n    at Object.parseConfigs (/usr/src/app/lib/config/index.js:109:20)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)"
       }
```

**Comment by rarkins** [comment]
Can you try like this as a workaround?

```
module.exports = {
	platform: 'gitlab',
	endpoint: 'https://private_gitlab/api/v4/',
	labels: ['renovate'],
	logLevel: 'info',
	docker: {"enabled": false },
	maven: {
	    "enabled": true,
	    "registryUrls": ["https://artifactoryurl1/", "https://artifactoryurl2/"]
	},
	hostRules: [{
	    "platform": "maven",
        "endpoint": "https://artifactoryurl1/",
	    "username": "artifactoryusername",
	    "password": "artifactorypassword"
	}, {
	    "platform": "maven",
        "endpoint": "https://artifactoryurl2/",
	    "username": "artifactoryusername",
	    "password": "artifactorypassword"
	}],
	onboardingConfig: { extends: ["config:base"] }
};
```

**Comment by 123Haynes** [comment]
@rarkins that worked, but it doesn't look like the registryUrls are being used at all.

```
DEBUG: Combined config
       "config": {
         "platform": "gitlab",
         "endpoint": "https://git.*private*/api/v4/",
         "baseBranches": ["master"],
         "labels": ["renovate"],
         "logLevel": "DEBUG",
         "docker": {"enabled": false},
         "maven": {
           "enabled": true,
           "registryUrls": [
             "https://artifactory.*private*/artifactory/ressource-maven-central/",
             "https://artifactory.*private*/artifactory/ressource-maven-oracle/"
           ]
         },
         "hostRules": [
           {
             "platform": "maven",
             "endpoint": "https://artifactory.*private*/artifactory/ressource-maven-central/",
             "username": "artifactoryusername",
             "password": "***********"
           },
           {
             "platform": "maven",
             "endpoint": "https://artifactory.*private*/artifactory/ressource-maven-oracle/",
             "username": "artifactoryusername",
             "password": "***********"
           },
           {
             "endpoint": "https://api.github.com/",
             "platform": "github",
             "token": "***********"
           }
         ],
         "onboardingConfig": {"extends": ["config:base"]},
         "token": "***********",
         "repositories": ["OBS/Backend", "OBS/Frontend", "UMA/uma-ga", "UMA/uma-gagui"]
       }
DEBUG: Setting hostRule
       "config": {
         "platform": "maven",
         "endpoint": "https://artifactory.*private*/artifactory/ressource-maven-central/",
         "username": "artifactoryusername",
         "password": "***********"
       }
DEBUG: Setting hostRule
       "config": {
         "platform": "maven",
         "endpoint": "https://artifactory.*private*/artifactory/ressource-maven-oracle/",
         "username": "artifactoryusername",
         "password": "***********"
       }
DEBUG: Setting hostRule
       "config": {
         "name": "GitHub",
         "endpoint": "https://api.github.com/",
         "platform": "github",
         "token": "***********"
       }
DEBUG: Setting hostRule
       "config": {
         "name": "GitLab",
         "endpoint": "https://git.*private*/api/v4/",
         "platform": "gitlab",
         "username": null,
         "password": null,
         "token": "***********"
       }
DEBUG: Setting hostRule
       "config": {
         "name": "GitLab",
         "endpoint": "https://git.*private*/api/v4/",
         "platform": "gitlab",
         "username": null,
         "password": null,
         "token": "***********",
         "default": true
       }
```

```
DEBUG: Url not found https://repo.maven.apache.org/maven2/com/oracle/jdbc/ojdbc8/maven-metadata.xml (repository=OBS/Backend)
DEBUG: com.oracle.jdbc:ojdbc8 not found in repository https://repo.maven.apache.org/maven2/ (repository=OBS/Backend)
 INFO: No versions found for com.oracle.jdbc:ojdbc8 in 1 repositories (repository=OBS/Backend)
 INFO: Failed to look up dependency com.oracle.jdbc:ojdbc8 (repository=OBS/Backend, packageFile=pom.xml, dependency=com.oracle.jdbc:ojdbc8)
```

**Comment by rarkins** [comment]
I think that the configured registryUrls are being overridden by the Maven extract function.

Can you try the following? i.e. add the urls to a packageRule instead.

```
module.exports = {
	platform: 'gitlab',
	endpoint: 'https://private_gitlab/api/v4/',
	labels: ['renovate'],
	logLevel: 'info',
	docker: {"enabled": false },
	maven: {
	    "enabled": true
	},
	hostRules: [{
	    "platform": "maven",
        "endpoint": "https://artifactoryurl1/",
	    "username": "artifactoryusername",
	    "password": "artifactorypassword"
	}, {
	    "platform": "maven",
        "endpoint": "https://artifactoryurl2/",
	    "username": "artifactoryusername",
	    "password": "artifactorypassword"
	}],
    "packageRules": [{
        "managers": ["maven"],
	    "registryUrls": ["https://artifactoryurl1/", "https://artifactoryurl2/"]
    }],
	onboardingConfig: { extends: ["config:base"] }
};
```

**Comment by rarkins** [comment]
Reopening despite the title now being irrelevant, but because otherwise I risk missing messages..

**Comment by 123Haynes** [comment]
@rarkins That worked perfectly :+1:   
I can confirm that authentication and multiple maven repos work just fine with this config.

What do you think about adding this config to an example folder in renovate/renovate or a separate repo?  
I think the usecase will be quite common for java developers wanting to use renovate and this config is not obvious from the docs at all.
Would you accept a PR for this?

If you have any other gitlab or maven related things you'd like to have tested, please ping me. I'll gladly test everything :smiley:

**Comment by rarkins** [comment]
That's great that it's working! I realised that I already needed to do a major update of Java documentation anyway so added in your example config while I was at it. It's now live here: https://renovatebot.com/docs/java/

I'd be very happy if you can let me know if you find any bugs or shortcomings with Maven support, or if you think it looks good. I'm considering to default it to enabled next week.

**Comment by rarkins** [comment]
For the record, we stumbled over a couple of config difficulties here:

### hostRules require endpoints

The hostRules failed the first time because they required you to enter an endpoint with the platform. I'm rewriting hostRules currently and will remove this limitation in future, so the original single rule I suggested will work.

### maven registryUrls get overwritten

This a harder problem to overcome, but I am working on a solution too. We will implicitly convert all manager objects (e.g. `"maven": {}`) into packageRules after the config is read in, that way it won't get rewritten.
