### ISSUE TITLE
[Question] Setting up Self Hosted GitHub 

### ISSUE THREAD

**Issue by vinicius-tona** [renovatebot/config-help#245]
### Which Renovate are you using? CLI, App, or Pro
CLI 

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
```
DEBUG: Using baseDir: /var/folders/vq/qsv92nys4xzdbh99_rll229sfyz7d4/T/renovate
DEBUG: Using cacheDir: /var/folders/vq/qsv92nys4xzdbh99_rll229sfyz7d4/T/renovate/cache
DEBUG: Using default git author (Renovate Bot)
DEBUG: Initializing Renovate internal cache into /var/folders/vq/qsv92nys4xzdbh99_rll229sfyz7d4/T/renovate/cache/renovate/renovate-cache-v1
 INFO: Renovating repository (repository=jive/com.jive.rtc.notification.e2e)
DEBUG: Using localDir: /var/folders/vq/qsv92nys4xzdbh99_rll229sfyz7d4/T/renovate/repos/github/jive/com.jive.rtc.notification.e2e (repository=jive/com.jive.rtc.notification.e2e)
 INFO: Init API (repository=jive/com.jive.rtc.notification.e2e)
DEBUG: initRepo("jive/com.jive.rtc.notification.e2e") (repository=jive/com.jive.rtc.notification.e2e)
DEBUG: Setting hostRule (repository=jive/com.jive.rtc.notification.e2e)
       "config": {
         "name": "GitHub",
         "endpoint": "https://github.com/",
         "platform": "github",
         "username": null,
         "password": null,
         "token": "***********",
         "default": true
       }
ERROR: Repository has unknown error (repository=jive/com.jive.rtc.notification.e2e)
       "err": {
         "name": "HTTPError",
         "hostname": "github.com",
         "method": "GET",
         "path": "/user",
         "protocol": "https:",
         "url": "https://github.com/user",
         "gotOptions": {
           "path": "/user",
           "protocol": "https:",
           "hostname": "github.com",
           "hash": "",
           "search": "",
           "pathname": "/user",
           "href": "https://github.com/user",
           "retry": {
             "methods": {},
             "statusCodes": {},
             "errorCodes": {},
             "maxRetryAfter": 60000
           },
           "headers": {
             "user-agent": "https://github.com/sindresorhus/gh-got",
             "accept": "application/vnd.github.v3+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "** redacted **"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "baseUrl": "https://github.com/",
           "name": "GitHub",
           "platform": "github",
           "username": null,
           "password": null,
           "token": "************",
           "default": true,
           "gotTimeout": {"request": 60000},
           "method": "GET"
         },
         "statusCode": 406,
         "statusMessage": "Not Acceptable",
         "headers": {
           "server": "GitHub.com",
           "date": "Wed, 22 May 2019 13:20:05 GMT",
           "content-type": "#<Mime::NullType:0x00007ff8cbdbf7d8>",
           "transfer-encoding": "chunked",
           "connection": "close",
           "status": "406 Not Acceptable",
           "vary": "X-PJAX",
           "cache-control": "no-cache",
           "set-cookie": [
             "has_recent_activity=1; path=/; expires=Wed, 22 May 2019 14:20:05 -0000",
             "logged_in=no; domain=.github.com; path=/; expires=Sun, 22 May 2039 13:20:05 -0000; secure; HttpOnly",
           ],
           "x-request-id": "*********",
           "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
           "content-security-policy": "********",
           "x-github-request-id": "********"
         },
         "body": "",
         "rateLimit": {"limit": null, "remaining": null, "reset": null},
         "message": "Response code 406 (Not Acceptable)",
         "stack": "HTTPError: Response code 406 (Not Acceptable)\n    at EventEmitter.emitter.on (/usr/local/lib/node_modules/renovate/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
```

### What is your question?
Hi, I'm trying to setup a self-hosted renovate with a GitHub account but I think I'm missing something. I followed [this guide](https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md) and created the following config
```  
  1 module.exports = {
  2   endpoint: 'https://github.com/',
  3   token: '***************',
  4   platform: 'github',
  5   logFileLevel: 'trace',
  6   logLevel: 'debug',
  7   logFile: '/Users/vtona/renovate.log',
  8   onboarding: true,
  9   onboardingConfig: {
 10     extends: ['config:base'],
 11   },
 12   repositories: ['jive/com.jive.rtc.notification.e2e'],
 13 };
``` 
but when I try to run the following script
``` 
  1 #!/bin/bash
  2
  3 export PATH="/Users/vtona/.yarn/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
  4 export RENOVATE_CONFIG_FILE="/Users/vtona/renovate-config.js"
  5 export RENOVATE_TOKEN="***************" # GitHub, GitLab, Azure DevOps
  6 #export GITHUB_COM_TOKEN="**github-token**" # Delete this if using github.com
  7
  8 # Renovate
  9 renovate
```

I ended up with the error posted above. 
I tried to debug this and saw that on `platform/github/index.js#getRenovateUsername` it does a `(await get('user')).body.login` and that would explain why it tries to access `https://github.com/user` but even if I skip that part by setting up the `global.renovateUsername` manually, I still get issues further on trying to access the repositories because it tries to access `https://github.com/repos/jive/com.jive.rtc.notification.e2e` instead of `https://github.com/jive/com.jive.rtc.notification.e2e`

Can anybody help me with that, please? I'm guessing I'm missing something on my config

**Comment by rarkins** [comment]
The platform should be https://api.github.com, but you can leave that configuration out anyway as Renovate already defaults to that

**Comment by vinicius-tona** [comment]
Thanks a lot, it worked!!
