### ISSUE TITLE
[Question] ERROR: Repository is not found

### ISSUE THREAD

**Issue by tisoft** [renovatebot/config-help#265]
### Which Renovate are you using? CLI, App, or Pro
CLI deployed to kubernetes

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Selfhosted Gitab

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {"logLevel": "debug"}
DEBUG: Env config
       "config": {
         "hostRules": [
           {"hostType": "github", "domainName": "github.com", "token": "***********"}
         ],
         "platform": "gitlab",
         "endpoint": "https://develop-ci1-lin.intern.example.com/gitlab/api/v4/",
         "token": "***********",
         "autodiscover": true,
         "gitAuthor": "Renovate Bot <renovate-bot@example.de>"
       }
DEBUG: Combined config
       "config": {
         "hostRules": [
           {"hostType": "github", "domainName": "github.com", "token": "***********"}
         ],
         "platform": "gitlab",
         "endpoint": "https://develop-ci1-lin.intern.example.com/gitlab/api/v4/",
         "token": "***********",
         "autodiscover": true,
         "gitAuthor": "Renovate Bot <renovate-bot@example.de>",
         "logLevel": "debug"
       }
 INFO: Using configured gitAuthor (Renovate Bot <renovate-bot@example.de>)
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
 INFO: Autodiscovering GitLab repositories
 INFO: Discovered 1 project(s)
 INFO: Discovered 1 repositories
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
 INFO: Renovating repository (repository=example/myapp-dsp)
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/example/myapp-dsp (repository=example/myapp-dsp)
DEBUG: Caught initRepo error (repository=example/myapp-dsp)
ERROR: Repository is not found (repository=example/myapp-dsp)
 INFO: Finished repository (repository=example/myapp-dsp)
DEBUG: Host request stats (milliseconds)
       "hostStats": {
         "develop-ci1-lin.intern.example.com": {
           "requests": 2,
           "sum": 149,
           "average": 75,
           "median": 30
         }
       }
 INFO: Renovate finished

```

### What is your question?
What can I do to get more information about the error:

```
DEBUG: Caught initRepo error (repository=example/myapp-dsp)
ERROR: Repository is not found (repository=example/myapp-dsp)
```

Manually cloning the repo does work with the same user.

**Comment by rarkins** [comment]
That's definitely confusing. It's made two requests to your gitlab server. The first one tells it the list of repos it has access to, and the second request seems to have returned a 404 for that repo. I have added an extra debug for initRepo in renovate@18.10.4 so once it's available on Docker Hub, please run with that to see an expanded log.

**Comment by rarkins** [comment]
Actually are you using the `renovate/renovate` Docker image, or building your own image using the npm `renovate`? It's published to npm but Docker Hub doesn't seem to have processed the webhook and isn't building 18.10.4

**Comment by tisoft** [comment]
I'm using the renovate/renovate docker image

**Comment by tisoft** [comment]
I have build it locally. This is the new debug output:

```
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {
         "repositories": ["example/myapp-dsp"],
         "dryRun": true,
         "printConfig": true,
         "logLevel": "debug",
         "platform": "gitlab",
         "endpoint": "https://develop-ci1-lin.intern.example.com/gitlab/api/v4",
         "token": "***********"
       }
DEBUG: Env config
       "config": {"hostRules": []}
DEBUG: Combined config
       "config": {
         "hostRules": [],
         "repositories": ["example/myapp-dsp"],
         "dryRun": true,
         "printConfig": true,
         "logLevel": "debug",
         "platform": "gitlab",
         "endpoint": "https://develop-ci1-lin.intern.example.com/gitlab/api/v4",
         "token": "***********"
       }
 INFO: Using default gitAuthor: Renovate Bot <bot@renovateapp.com>
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
 INFO: Renovating repository (repository=example/myapp-dsp)
DEBUG: Using localDir: /tmp/renovate/repos/gitlab/example/myapp-dsp (repository=example/myapp-dsp)
DEBUG: Caught initRepo error (repository=example/myapp-dsp)
       "err": {
         "name": "HTTPError",
         "hostname": "develop-ci1-lin.intern.example.com",
         "method": "GET",
         "path": "/gitlab/api/v4/projects/example%2Fmyapp-dsp",
         "protocol": "https:",
         "url": "https://develop-ci1-lin.intern.example.com/gitlab/api/v4/projects/example%2Fmyapp-dsp",
         "gotOptions": {
           "path": "/gitlab/api/v4/projects/example%2Fmyapp-dsp",
           "protocol": "https:",
           "hostname": "develop-ci1-lin.intern.example.com",
           "hash": "",
           "search": "",
           "pathname": "/gitlab/api/v4/projects/example%2Fmyapp-dsp",
           "href": "https://develop-ci1-lin.intern.example.com/gitlab/api/v4/projects/example%2Fmyapp-dsp",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate",
             "Private-token": "XXXXX"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "hostType": "gitlab",
           "baseUrl": "https://develop-ci1-lin.intern.example.com/gitlab/api/v4/",
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "date": "Wed, 05 Jun 2019 17:09:28 GMT",
           "server": "nginx",
           "content-type": "application/json",
           "content-length": "35",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-content-type-options": "nosniff",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "TQv1uLwwYg5",
           "x-runtime": "0.013445",
           "connection": "close"
         },
         "body": {"message": "404 Project Not Found"},
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/usr/src/app/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
ERROR: Repository is not found (repository=example/myapp-dsp)
 INFO: Finished repository (repository=example/myapp-dsp)
DEBUG: Host request stats (milliseconds)
       "hostStats": {
         "develop-ci1-lin.intern.example.com": {
           "requests": 1,
           "sum": 517,
           "average": 517,
           "median": 517
         }
       }
 INFO: Renovate finished

```

The %2F seem to be wrong in my opinion. I think they should be /, shouldn't they?

(The private-token wan't hidden, I did that manually)

**Comment by rarkins** [comment]
Actually I may remember this problem from before. GitLab *does* require the %2f, but if you have a reverse proxy in front of it that converts the %2f to `/` then gitlab rejects it. Is that a possibility?

**Comment by tisoft** [comment]
Thanks!

That was the problem. Now I need to figure out the next one. :smile:

**Comment by tisoft** [comment]
Ok... it now tries to clone from https://**redacted**@develop-ci1-lin.intern.example.com/example/myapp-dsp.git/ but the correct URI would be: https://**redacted**@develop-ci1-lin.intern.example.com/gitlab/example/myapp-dsp.git/ That URI is also given back in the API JSON.

**Comment by rarkins** [comment]
Is your web proxy responsible for that `/example/` mapping?

**Comment by tisoft** [comment]
The gitlab is behind a proxy that adds the /gitlab/ path as prefix.

I just editet the source to the following:
```
    const url = GitStorage.getUrl({
      protocol: protocol!.slice(0, -1) as any,
      auth: 'oauth2:' + opts.token,
      host,
      repository: 'gitlab/' + repository,
    });
```

After that at least the dry run successfully runs through. Of course this is not a general solution. The correct base url can be found in the API output in the field ```http_url_to_repo```. Would you be willing to accept a patch, that evaluates that field and adds support for gitlab instances behind a proxy with nested context root?

**Comment by rarkins** [comment]
Happy to get a PR if it can satisfy both the regular case as well as ones like yours.
