### ISSUE TITLE
Timeout awaiting 'request' for 60000ms

### ISSUE THREAD

**Issue by aethanol** [renovatebot/config-help#268]
### Which Renovate are you using? CLI, App, or Pro
CLI, running with `LOG_LEVEL=debug renovate` with a `config.js` in the directory.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket Server

### Config
```
module.exports = {
  endpoint: '<redacted>', // included trailing slash
  platform: 'bitbucket-server',
  username: '<redacted>',
  password:'<redacted>',
  onboarding: true,
  gitAuthor: "Renovate Bot <bot@renovateapp.com>",
  onboardingConfig: {
    extends: ['config:base'],
  },
  repositories: [ '<redacted>' ],
  includeForks: true,
};
```

### Logs
```
ERROR: Repository has unknown error (repository=<redacted>)
       "err": {
         "name": "TimeoutError",
         "code": "ETIMEDOUT",
         "host": "<redacted>",
         "hostname": "<redacted>",
         "method": "GET",
         "path": "<redacted>",
         "protocol": "https:",
         "url": "<redacted>",
         "gotOptions": {
           "path": "<redacted>",
           "protocol": "https:",
           "slashes": true,
           "auth": "<redacted>",
           "host": "<redacted>",
           "port": null,
           "hostname": "<redacted>",
           "hash": null,
           "search": "?state=ALL&limit=100",
           "pathname": "<redacted>",
           "href": "<redacted>",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "x-atlassian-token": "no-check",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "hostType": "bitbucket-server",
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "event": "request",
         "message": "Timeout awaiting 'request' for 60000ms",
         "stack": "TimeoutError: Timeout awaiting 'request' for 60000ms\n    at ClientRequest.request.once.error (/Users/eanderson/.nvm/versions/node/v10.8.0/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:176:14)\n    at Object.onceWrapper (events.js:273:13)\n    at ClientRequest.emit (events.js:187:15)\n    at ClientRequest.origin.emit.args (/Users/eanderson/.nvm/versions/node/v10.8.0/lib/node_modules/renovate/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at Immediate.timeoutHandler (/Users/eanderson/.nvm/versions/node/v10.8.0/lib/node_modules/renovate/node_modules/got/source/utils/timed-out.js:63:11)\n    at runCallback (timers.js:694:11)\n    at tryOnImmediate (timers.js:664:5)\n    at processImmediate (timers.js:646:5)"
       }
```

### What is your question?
Is there something in the configuration that I'm not setting properly?
I'm setting the endpoint _without_ the /rest/api, as it seems it is different than the github config.
Thanks!

**Comment by rarkins** [comment]
Does it time out at the exact same request every time? Is that the first request it performs? Basically that's just saying that the host is unreachable because we couldn't connect after 60s, which is the default timeout.

**Comment by aethanol** [comment]
Hmm, yeah getting the same timeout every time. Weirdly enough, I am able to curl the same endpoint from the url field with my provided credentials! Also, it is getting past the clone step so I'm a bit confused.

**Comment by aethanol** [comment]
Though, actually I recall that I was getting a different error for a bit `ECONNRESET`

```
"err": {
         "name": "RequestError",
         "code": "ECONNRESET",
          .....
          "message": "read ECONNRESET",
         "stack": "RequestError: read ECONNRESET\n    at ClientRequest.request.once.error (/Users/eanderson/.nvm/versions/node/v10.8.0/lib/node_modules/renovate/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:273:13)\n    at ClientRequest.emit (events.js:187:15)\n    at ClientRequest.origin.emit.args (/Users/eanderson/.nvm/versions/node/v10.8.0/lib/node_modules/renovate/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:382:9)\n    at TLSSocket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
}
```
