### ISSUE TITLE
About "Action Required: Fix Renovate Configuration"

### ISSUE THREAD

**Issue by FantasticFiasco** [renovatebot/config-help#306]
### Which Renovate are you using? CLI, App, or Pro
- App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
- GitHub

### Have you checked the logs? Don't forget to include them if relevant
```
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "github>FantasticFiasco/renovate-config"
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>FantasticFiasco/renovate-config"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>FantasticFiasco/renovate-config"
    ]
  }
}
DEBUG: Failed to retrieve default.json from repo
INFO: default.json preset not found - trying renovate.json
DEBUG: Failed to retrieve renovate.json from repo
DEBUG: Preset fetch error
{
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at fetchJSONFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/github/index.js:24:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
INFO: Throwing preset error
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (github>FantasticFiasco/renovate-config)"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, null, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 41 Pull Requests
DEBUG: ensureIssue()
INFO: Reopening previously closed issue
INFO: Patching issue
INFO: Issue updated
```

### What is your question?
Every now and again Renovate is opening an issue in all my configured repositories claiming that the configuration is invalid. Then a couple of hours later the issue is closed again.

**Comment by rarkins** [comment]
Can you locate a job ID from the dashboard where such an issue is opened?

**Comment by FantasticFiasco** [comment]
Absolutely, here it is: FantasticFiasco/serilog-sinks-http: #82069330

Thank you very much for such a quick response!

**Comment by FantasticFiasco** [comment]
A fellow Swede, nice meeting you!
