### ISSUE TITLE
Ruby Configuration Help needed

### ISSUE THREAD

**Issue by shushugah** [renovatebot/config-help#336]
### What are your question(s)?
I have three questions.

1. How can I debug and understand better what is happening locally? 
2. How can I give it access to private ruby gem directories? I get an error that it quits during registry step as pasted below in logs `INFO: Registry error - skipping (repository=payment/payment-api)` for the payment-api repository. It succesfully creates a merge request, for a Docker image. 
3. Separately, it seems to expect a `.ruby_version` file when `bundler: { enabled: true }` is included. This is not documented, but I read through the source code. 

### Which Renovate are you using? CLI, App, or Pro

CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitLab EE

### Have you checked the logs? Don't forget to include them if relevant

Not sure how to find them, but here is what errors state in terminal
```bash
 INFO: Using platform gitAuthor: yonatan.miller@redacted.com
 INFO: Renovating repository (repository=payment/payment-api)
 INFO: Initialising git repository into /tmp/renovate/repos/gitlab/payment/payment-api (repository=payment/payment-api)
 INFO: git clone completed (repository=payment/payment-api)
       "cloneSeconds": 5
 INFO: Setting git author (repository=payment/payment-api)
       "gitAuthor": {"name": null, "email": "yonatan.miller@redacted.com"}
 INFO: baseBranches (repository=payment/payment-api)
       "baseBranches": ["master"]
 INFO: Found bundler package files (repository=payment/payment-api)
 INFO: Found docker-compose package files (repository=payment/payment-api)
 INFO: Found dockerfile package files (repository=payment/payment-api)
 INFO: Found gitlabci package files (repository=payment/payment-api)
 INFO: Registry error - skipping (repository=payment/payment-api)
 INFO: Finished repository (repository=payment/payment-api)
 INFO: Renovate finished
```

### Current setup 
```js
// config.js

module.exports = {
  platform: 'gitlab',
  endpoint: 'http://gitlab.redacted:10087/api/v4/',
  assignees: [],
  baseBranches: ['master'],
  labels: ['renovate', 'payment'],
  extends: ['config:base'],
  onboarding: false,
  trustLevel: 'high',
  requireConfig: false,
  bundler: { enabled: true },
  // https://en.wikipedia.org/wiki/1729_(number)
  commitMessagePrefix: 'PAY-1729',
  branchPrefix: 'PAY-1729-Renovate',
  branchTopic: '{{{depNameSanitized}}}-{{{newMajor}}}{{#if isPatch}}-{{{newMinor}}}{{/if}}-x{{#if isLockfileUpdate}}-lockfile{{/if}}',
  prHourlyLimit: 6,
  token: process.env.GITLAB_TOKEN,
  repositories: [
    'payment/payment-api'
  ]
}
```

and inside my Dockerfile
```
FROM renovate/renovate:latest@sha256:21a6f6cf6b18d22aa7ee15e2f2a6a25f1bc5c2ed03da069034d2b1bfb2bb8030

ENV GITLAB_TOKEN=$GITLABTOKEN

COPY ./config.js /usr/src/app/config.js
```

**Comment by rarkins** [comment]
1. Run with LOG_LEVEL=debug for much more detailed logging. or logLevel=‘debug’ in your config.js

You’ll also need hostRules for authentication to get the lookups going. Please search the docs for examples of hostRules

**Comment by rarkins** [comment]
Also, Renovate doesn't expect/require a `.ruby_version` file but if one is present then it uses it to guess at the best version of Ruby to run `bundle` within. If no version of Ruby is found anywhere in the repo then it will run with the latest stable version.

**Comment by shushugah** [comment]
I will continue here. Running this locally in debugger mode:

```
docker build -t yolo .
docker run yolo:latest
```
and passing it a repository named `test-gems` repo, which only has a `Gemfile` and `Gemfile.lock` and a `.ruby-version` file of 2.6.3. The Gemfile simply contains:

```ruby
# Gemfile
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'
gem 'rails', '~> 5.2.1'
gem 'puma'
```

```bash
DEBUG: Updating packageFile content (repository=payment/test-gems, dependencies=rails, branch=PAY-1729-Renovaterails-6-x)
DEBUG: bundler.updateArtifacts(Gemfile) (repository=payment/test-gems, dependencies=rails, branch=PAY-1729-Renovaterails-6-x)
 INFO: Running bundler via global bundler (repository=payment/test-gems, dependencies=rails, branch=PAY-1729-Renovaterails-6-x)
DEBUG: bundler command (repository=payment/test-gems, dependencies=rails, branch=PAY-1729-Renovaterails-6-x)
       "cmd": "bundle lock --update rails"
 WARN: Failed to generate Gemfile.lock (unknown error) (repository=payment/test-gems, dependencies=rails, branch=PAY-1729-Renovaterails-6-x)
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "bundle lock --update rails",
         "stdout": "",
         "stderr": "/bin/sh: 1: bundle: not found\n",
         "message": "Command failed: bundle lock --update rails\n/bin/sh: 1: bundle: not found\n",
         "stack": "Error: Command failed: bundle lock --update rails\n/bin/sh: 1: bundle: not found\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Socket.stream.socket.on (internal/child_process.js:389:11)\n    at Socket.emit (events.js:198:13)\n    at Pipe._handle.close (net.js:606:12)"
       }
DEBUG: branchPrefix: PAY-1729-Renovate (repository=payment/test-gems)
DEBUG: Found 0 Renovate PRs (repository=payment/test-gems)
       "renovatePrs": []
DEBUG: Removing any stale branches (repository=payment/test-gems)
DEBUG: config.repoIsOnboarded=true (repository=payment/test-gems)
DEBUG: No renovate branches found (repository=payment/test-gems)
DEBUG: ensureIssueClosing() (repository=payment/test-gems)
 INFO: Finished repository (repository=payment/test-gems)
DEBUG: Host request stats (milliseconds)
       "hostStats": {
         "registry.npmjs.org": {
           "requests": 6,
           "sum": 464,
           "average": 77,
           "median": 45
         },
         "gitlab.car2go.own": {
           "requests": 5,
           "sum": 1103,
           "average": 221,
           "median": 394
         },
         "rubygems.org": {"requests": 1, "sum": 344, "average": 344, "median": 344},
         "www.ruby-lang.org": {
           "requests": 1,
           "sum": 364,
           "average": 364,
           "median": 364
         }
       }
 INFO: Renovate finished
```

**Comment by rarkins** [comment]
I don't understand what you're doing. What's `yolo`?

**Comment by shushugah** [comment]
I am running Renovate on my local machine with Docker, so that I can quickly rebuild my docker image (arbitrarily nicknamed `yolo`) here. 

My Dockerfile contains:
```Docker
# Dockerfile
FROM renovate/renovate:latest
ENV GITLAB_TOKEN=$GITLABTOKEN
COPY ./config.js /usr/src/app/config.js
```

and my config.js contains

```javascript
// config.js
module.exports = {
  logLevel: 'debug',
  platform: 'gitlab',
  endpoint: 'http://gitlab.redacted:10087/api/v4/',
  assignees: [],
  baseBranches: ['master'],
  labels: ['renovate', 'payment'],
  extends: ['config:base'],
  onboarding: false,
  trustLevel: 'high',
  requireConfig: false,
  bundler: { enabled: true },
  // https://en.wikipedia.org/wiki/1729_(number)
  commitMessagePrefix: 'PAY-1729',
  branchPrefix: 'PAY-1729-Renovate',
  branchTopic: '{{{depNameSanitized}}}-{{{newMajor}}}{{#if isPatch}}-{{{newMinor}}}{{/if}}-x{{#if isLockfileUpdate}}-lockfile{{/if}}',
  prHourlyLimit: 6,
  token: process.env.GITLAB_TOKEN,
  repositories: [
    'payment/test-gems'
  ]
}

```

**Comment by rarkins** [comment]
Thanks, now I understand. We don't package any Ruby or Bundler into our standard distribution as you always need to run the exact same one as is used by developers/CI. It works if either:

1. You run via CLI with `--binary-source=docker`, or
2. You install Ruby/bundler into your Dockerfile, extending renovate/renovate

**Comment by rarkins** [comment]
This is another possibility that may work for you: https://github.com/renovatebot/renovate/issues/3153#issuecomment-524881083

But we are still in the process of testing/verifying it. Essentially you run the "slim" image of Renovate and it then spawns sibling containers using the mapped docker sock.
