### ISSUE TITLE
private npm registry support - unable to authenticate 

### ISSUE THREAD

**Issue by sumanapotturu** [renovatebot/config-help#343]
### Which Renovate are you using?
App

### Which platform are you using?
GitHub

### What is your question?
renovate is able to connect to artifactory and get the upgraded version but throws authentication error on npm install
```
node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit
```
This is my current config 
```
{
  "config": {
    "encrypted": {
      "npmrc": "***********"
    },
    "registryUrls": [
      "//artifactory-endpoint"
    ],
    "npm": {
      "enabled": true
    },
    "hostRules": [
      {
        "username": "*******",
        "encrypted": {
          "password": "***********"
        },
        "baseUrl": "//artifactory-endpoint"
      }
    ]
  }
}
```
package.json
```
  "devDependencies": {
    "audit-ci": "2.2.0"
  }
```

### Have you checked the logs? Don't forget to include them if relevant
Successfully getting upgrade version
```
    "npm": [
      {
        "packageFile": "package.json",
        "manager": "npm",
        "deps": [
          {
            "depType": "devDependencies",
            "depName": "audit-ci",
            "currentValue": "2.2.0",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "2.2.0",
            "updates": [
              {
                "fromVersion": "2.2.0",
                "toVersion": "2.3.0",
                "newValue": "2.3.0",
                "newMajor": 2,
                "newMinor": 3,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "2019-08-30T16:24:25.062Z",
                "canBeUnpublished": true
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/IBM/audit-ci"
          }
        ],
```

NPM install error
```
DEBUG: Using npm: node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit(branch="renovate/audit-ci-2.x")
INFO: lock file error(branch="renovate/audit-ci-2.x")
{
  "cmd": "node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js",
  "args": "install --package-lock-only --no-audit",
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit",
    "stdout": "",
    "stderr": "npm ERR! code E401\nnpm ERR! Unable to authenticate, need: Basic realm=\"Artifactory Realm\"\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/\n",
    "message": "Command failed: node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\nnpm ERR! code E401\nnpm ERR! Unable to authenticate, need: Basic realm=\"Artifactory Realm\"\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/\n",
    "stack": "Error: Command failed: node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\nnpm ERR! code E401\nnpm ERR! Unable to authenticate, need: Basic realm=\"Artifactory Realm\"\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  },
  "stdout": "",
  "stderr": "",
  "type": "npm"
}
```

**Comment by rarkins** [comment]
It looks like your hostRule is being used to successfully look up the dependency versions but the npmrc is not providing npm with the credentials it needs. Look through the logs for all mentions of npmrc to see if there’s any hints

**Comment by sumanapotturu** [comment]
```
DEBUG: Writing repo .npmrc (/mnt/renovate/gh/<repository path>)(branch="renovate/audit-ci-2.x")
```
There are no errors here, seems to be able to write .npmrc successfully. I passed unencrypted .npmrc just to make encrypted npmrc is not a problem, but that doesn't seem to work either. 
I ran it on the same repository locally, and package-lock was generated with no issues

**Comment by rarkins** [comment]
When you run locally, how is npm getting the artifactory credentials? Eg from your home directory?

**Comment by sumanapotturu** [comment]
Has to be from renovate config file. I cleared `~/.npmrc` config to be sure credentials are not being read from there.

**Comment by rarkins** [comment]
You can if you use scoped package names
