### ISSUE TITLE
[Question] Cannot find preset's package

### ISSUE THREAD

**Issue by mrlubos** [renovatebot/config-help#347]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Renovating repository
DEBUG: Using localDir: /mnt/renovate/gh/helix-re/folio-web
DEBUG: initRepo("helix-re/folio-web")
INFO: Authenticated as user: renovate[bot]
INFO: Using renovate version: 19.36.4
DEBUG: helix-re/folio-web owner = helix-re
DEBUG: helix-re/folio-web default branch = master
DEBUG: Using app token for git init
INFO: Initialising git repository into /mnt/renovate/gh/helix-re/folio-web
INFO: git clone completed
{
  "cloneSeconds": 1.6
}
DEBUG: latest commit
{
  "latestCommitDate": "2019-09-02 15:55:38 +0100"
}
DEBUG: Git private key configured, but not being set
INFO: Setting git author
{
  "gitAuthor": {
    "name": "Renovate Bot",
    "email": "bot@renovateapp.com"
  }
}
DEBUG: resetMemCache()
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: Semantic commits detection: unknown
DEBUG: No semantic commits detected
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: config file exists
DEBUG: ensureIssueClosing(Action required: Add a Renovate config)
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "github>helix-re/renovate-config"
    ],
    "reviewers": []
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "github>helix-re/renovate-config"
    ],
    "reviewers": []
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "github>helix-re/renovate-config"
    ],
    "reviewers": []
  }
}
DEBUG: Failed to retrieve default.json from repo
INFO: default.json preset not found - trying renovate.json
DEBUG: Failed to retrieve renovate.json from repo
DEBUG: Preset fetch error
{
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at fetchJSONFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/github/index.js:30:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
INFO: Throwing preset error
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (github>helix-re/renovate-config)"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, null, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 968 Pull Requests
DEBUG: ensureIssue()
INFO: Patching issue
INFO: Issue updated
INFO: Finished repository
```

### What is your question?

Our shared configuration lives in a private repository on Github. The `package.json` includes `renovate-config` object with the key `default` and a file called `default.json` that includes the same contents as `package.json>renovate-config>default`. How can I fix this please?

**Comment by rarkins** [comment]
You need to make sure Renovate has access to that repo. It’s ok to decline the onboarding pull request to disable renovating it, but it must have access in order to read the files

**Comment by mrlubos** [comment]
@rarkins Hey, thanks for the prompt response! How can I verify if Renovate has access to the repository?

**Comment by rarkins** [comment]
Have the org admin go to GitHub.com/apps/renovate and check which repos it’s installed into (scroll to bottom IIRC)

**Comment by mrlubos** [comment]
Thanks a lot @rarkins!
