### ISSUE TITLE
[Question] Private ruby gem: Host key verification failed

### ISSUE THREAD

**Issue by Scritik** [renovatebot/config-help#357]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant

<details>
<summary>Details</summary>

```
WARN: Failed to generate Gemfile.lock (unknown error)(branch="renovate/activerecord-6.x")
{
  "err": {
    "killed": false,
    "code": 11,
    "signal": null,
    "cmd": "docker run --rm -v /mnt/renovate/gh/xxxxx/the-main-repo:/mnt/renovate/gh/xxxxx/the-main-repo -w /mnt/renovate/gh/xxxxx/the-main-repo renovate/ruby:latest bash -l -c \"ruby --version && gem install bundler -v 2.0.2 --no-document && bundle lock --update activerecord\"",
    "stdout": "ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]\nSuccessfully installed bundler-2.0.2\n1 gem installed\nFetching git@github.com:xxxxx/the-private-gem.git\n\n\n\n\n",
    "stderr": "Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nGit error: command `git clone 'git@github.com:xxxxx/the-private-gem.git'\n\"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\"\n--bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has\nfailed.\n",
    "message": "Command failed: docker run --rm -v /mnt/renovate/gh/xxxxx/the-main-repo:/mnt/renovate/gh/xxxxx/the-main-repo -w /mnt/renovate/gh/xxxxx/the-main-repo renovate/ruby:latest bash -l -c \"ruby --version && gem install bundler -v 2.0.2 --no-document && bundle lock --update activerecord\"\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nGit error: command `git clone 'git@github.com:xxxxx/the-private-gem.git'\n\"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\"\n--bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has\nfailed.\n",
    "stack": "Error: Command failed: docker run --rm -v /mnt/renovate/gh/xxxxx/the-main-repo:/mnt/renovate/gh/xxxxx/the-main-repo -w /mnt/renovate/gh/xxxxx/the-main-repo renovate/ruby:latest bash -l -c \"ruby --version && gem install bundler -v 2.0.2 --no-document && bundle lock --update activerecord\"\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nRetrying `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:xxxxx/the-private-gem.git' \"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\" --bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has failed.\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nGit error: command `git clone 'git@github.com:xxxxx/the-private-gem.git'\n\"/usr/local/lib/ruby/gems/2.6.0/cache/bundler/git/the-private-gem-2ec564e1b1d2af42a20b1e5230aee9d6876377b3\"\n--bare --no-hardlinks --quiet` in directory /mnt/renovate/gh/xxxxx/the-main-repo has\nfailed.\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  }
}
```
</details>

### What is your question?
Hi,

I tried again to add renovate for a ruby project and the gemfile seems to be parsed correctly now.
The issue is that we have a private ruby gem, hosted on a private repo. I gave renovate access to this repo too but it seems that it can't fetch the content. Am I missing something?

Thanks

**Comment by rarkins** [comment]
Do you mean it's a gem hosted on a private github.com repository? And that you've installed Renovate into that repo too, so that Renovate has access? And by failure to you mean the "bundle update" command fails?

**Comment by Scritik** [comment]
Yep, this is a gem hosted on a private Github repo. I added access to this repo in Renovate (but it's not configured). The bundle update tries to fetch the repo and fails (Host key verification failed). You have all the details in the logs sections of my first message.
