### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by fullstackzach** [renovatebot/config-help#363]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: getManifestResponse(https://internal-registry.com:5000, docker-image, ea87f50fbdf3ff43e8bf93596edbe56e3071530f) (repository=namespace/repository)
 WARN: Error obtaining docker token (repository=namespace/repository)
       "registry": "https://internal-registry.com:5000",
       "dockerRepository": "repository",
       "err": {
         "name": "RequestError",
         "code": "EPROTO",
         "host": "internal-registry.com:5000",
         "hostname": "internal-registry.com",
         "method": "GET",
         "path": "/v2/",
         "protocol": "https:",
         "url": "https://internal-registry.com:5000/v2/",
         "gotOptions": {
           "path": "/v2/",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "internal-registry.com:5000",
           "port": "5000",
           "hostname": "internal-registry.com",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/v2/",
           "href": "https://internal-registry.com:5000/v2/",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": false,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "message": "write EPROTO 140372905225544:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
         "stack": "RequestError: write EPROTO 140372905225544:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n\n    at ClientRequest.request.once.error (/builds/user/renovate/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/builds/user/renovate/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at errorOrDestroy (internal/streams/destroy.js:107:12)\n    at onwriteError (_stream_writable.js:436:5)\n    at onwrite (_stream_writable.js:461:5)\n    at _destroy (internal/streams/destroy.js:49:7)\n    at TLSSocket.Socket._destroy (net.js:613:3)\n    at TLSSocket.destroy (internal/streams/destroy.js:37:8)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)"
       }
 INFO: No docker auth found - returning (repository=namespace/repository)
 INFO: Could not getDigest (repository=namespace/repository)
```

### What is your question?

I am trying to setup renovate to update at our pinned digests in Dockerfiles, but the internal docker registry does not support TLS. I understand the above error occurs `SSL routines:ssl3_get_record:wrong version` if you are trying to use TLS against a resource that does not support tLS

I tried setting up a `hostRules` config rule in `config.js`, to force this host to use http but I can't seem to get that to work, and continue to run into the above error
```
module.exports = {
  hostRules: [
    {
      hostType: 'docker',
      baseUrl: 'http://internal-registry.com:5000',
    },
  ],
};
```

Ideally I understand our registry should be configured to support TLS, but that will require a bit more effort in the short term.

Any advice on how to achieve this in the config?

**Comment by rarkins** [comment]
Here's where we assume https if no prefix is set: https://github.com/renovatebot/renovate/blob/4c78f5d51aa4636f0d53e132fa4108975fb901cd/lib/datasource/docker/index.ts#L33

Could you experiment with specifying the full URL in your docker image including http:// prefix?

**Comment by fullstackzach** [comment]
Hey @rarkins - thank you for being so responsive! I've opened issues in other open source projects and sometimes don't hear back for a couple of weeks, I think it's awesome you get back right away.

I tried adding `http://` in my Dockerfile like this

```
FROM http://internal-registry.com:5000/dockerrepo:ea87f50fbdf3ff43e8bf93596edbe56e3071530f
```
I wondered if this was a valid reference so I tried to run `docker build .` and saw the following error

```
Sending build context to Docker daemon  5.172MB
Step 1/13 : FROM http://internal-registry.com:5000/dockerrepo:ea87f50fbdf3ff43e8bf93596edbe56e3071530f
invalid reference format
```

I tried running Renovate against this repo and saw the following error:
```
DEBUG: getManifestResponse(https://index.docker.io, internal-registry.com:5000/dockerrepo, ea87f50fbdf3ff43e8bf93596edbe56e3071530f) (repository=namespace/repo)
 INFO: Docker Manifest is unknown (repository=namespace/repo)
       "err": {
         "name": "HTTPError",
         "host": "index.docker.io",
         "hostname": "index.docker.io",
         "method": "GET",
         "path": "/v2/http://internal-registry.com:5000/dockerrepo/manifests/ea87f50fbdf3ff43e8bf93596edbe56e3071530f",
         "protocol": "https:",
         "url": "https://index.docker.io/v2/http://internal-registry.com:5000/dockerrepo/manifests/ea87f50fbdf3ff43e8bf93596edbe56e3071530f",
         "gotOptions": {
           "path": "/v2/http://internal-registry.com:5000/dockerrepo/manifests/ea87f50fbdf3ff43e8bf93596edbe56e3071530f",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "index.docker.io",
           "port": null,
           "hostname": "index.docker.io",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/v2/http://internal-registry.com:5000/dockerrepo/manifests/ea87f50fbdf3ff43e8bf93596edbe56e3071530f",
           "href": "https://index.docker.io/v2/http://internal-registry.com:5000/dockerrepo/manifests/ea87f50fbdf3ff43e8bf93596edbe56e3071530f",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "authorization": "** redacted **",
             "accept": "application/vnd.docker.distribution.manifest.v2+json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": false,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "content-type": "text/plain; charset=utf-8",
           "docker-distribution-api-version": "registry/2.0",
           "x-content-type-options": "nosniff",
           "date": "Mon, 23 Sep 2019 14:15:32 GMT",
           "content-length": "19",
           "connection": "close",
           "strict-transport-security": "max-age=31536000"
         },
         "body": "404 page not found\n",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/builds/namespace/renovate/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       },
       "registry": "https://index.docker.io",
       "dockerRepository": "http://internal-registry.com:5000/dockerrepo",
       "tag": "ea87f50fbdf3ff43e8bf93596edbe56e3071530f"
 INFO: Could not getDigest (repository=namespace/repo)
       "newValue": "ea87f50fbdf3ff43e8bf93596edbe56e3071530f"
```

It looks like this breaks the pattern you're expecting in renovate too. 

I'm wondering if some kind of config option would need to be added to renovate to specify http in hostRules?

**Comment by rarkins** [comment]
Thanks for testing it out.

I think ideally we should emulate the docker client’s approach as closely as possible. I wondered if it just fell back to http if https is not found however that would be at risk of MITM attacks. I looked this up and it appears you need to opt into http pretty explicitly: https://docs.docker.com/registry/insecure/

Is that your experience in dev?

**Comment by fullstackzach** [comment]
Yes. I have it set to specify the `insecure-registries` in my docker client's `daemon.json`. Otherwise if I remove that, when it tries to fetch I get the error

```
Step 1/13 : FROM insecure-registry.com:5000/dockerrepo:ea87f50fbdf3ff43e8bf93596edbe56e3071530f
Get https://insecure-registry.com:5000/v2/: http: server gave HTTP response to HTTPS client
```
