### ISSUE TITLE
Docker daemon error trying to update gradle dependencies

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#417]
### Which Renovate are you using? CLI, App, or Pro
CLI using Docker image renovate/renovate:slim

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Using file match: \.gradle(\.kts)?$ for manager gradle (repository=rvillane/renovate-gradle-test)
 DEBUG: Using file match: (^|/)gradle.properties$ for manager gradle (repository=rvillane/renovate-gradle-test)
 DEBUG: Matched 2 file(s) for manager gradle: build.gradle, settings.gradle (repository=rvillane/renovate-gradle-test)
  INFO: Extracting dependencies from all gradle files (repository=rvillane/renovate-gradle-test)
 DEBUG: Creating renovate-plugin.gradle file with renovate gradle plugin (repository=rvillane/renovate-gradle-test)
 DEBUG: Start gradle command (repository=rvillane/renovate-gradle-test)
        "cmd": "docker run --rm -v /tmp/renovate/repos/github/rvillane/renovate-gradle-test:/tmp/renovate/repos/github/rvillane/renovate-gradle-test -w /tmp/renovate/repos/github/rvillane/renovate-gradle-test renovate/gradle gradle --init-script renovate-plugin.gradle renovate"
  WARN: Gradle command docker run --rm -v /tmp/renovate/repos/github/rvillane/renovate-gradle-test:/tmp/renovate/repos/github/rvillane/renovate-gradle-test -w /tmp/renovate/repos/github/rvillane/renovate-gradle-test renovate/gradle gradle --init-script renovate-plugin.gradle renovate failed. Exit code: 125. (repository=rvillane/renovate-gradle-test)
        "err": {
          "killed": false,
          "code": 125,
          "signal": null,
          "cmd": "docker run --rm -v /tmp/renovate/repos/github/rvillane/renovate-gradle-test:/tmp/renovate/repos/github/rvillane/renovate-gradle-test -w /tmp/renovate/repos/github/rvillane/renovate-gradle-test renovate/gradle gradle --init-script renovate-plugin.gradle renovate",
          "stdout": "",
          "stderr": "docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n",
          "message": "Command failed: docker run --rm -v /tmp/renovate/repos/github/rvillane/renovate-gradle-test:/tmp/renovate/repos/github/rvillane/renovate-gradle-test -w /tmp/renovate/repos/github/rvillane/renovate-gradle-test renovate/gradle gradle --init-script renovate-plugin.gradle renovate\ndocker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n",
          "stack": "Error: Command failed: docker run --rm -v /tmp/renovate/repos/github/rvillane/renovate-gradle-test:/tmp/renovate/repos/github/rvillane/renovate-gradle-test -w /tmp/renovate/repos/github/rvillane/renovate-gradle-test renovate/gradle gradle --init-script renovate-plugin.gradle renovate\ndocker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
        }
  INFO: Aborting Renovate due to Gradle lookup errors (repository=rvillane/renovate-gradle-test)
  INFO: Registry error - skipping (repository=rvillane/renovate-gradle-test)
  INFO: Finished repository (repository=rvillane/renovate-gradle-test)
 DEBUG: Host request stats (milliseconds)
        "hostStats": {
          "api.github.com": {"requests": 6, "sum": 3097, "average": 516, "median": 435},
          "registry.npmjs.org": {
            "requests": 6,
            "sum": 4116,
            "average": 686,
            "median": 723
          }
        }
  INFO: Renovate finished

```

### What is your question?
Clearly I'm doing something wrong, can you please help figure it out?

This is my Dockerfile
```
FROM renovate/renovate:slim

USER root
RUN mkdir /dist
RUN chown -R ubuntu:ubuntu /dist
WORKDIR /dist

COPY renovate-config-gradle.js  /dist/
ENV LOG_LEVEL=debug
ENV RENOVATE_CONFIG_FILE=/dist/renovate-config-gradle.js
USER ubuntu
```

And this is the renovate-config-gradle.js

```
module.exports = {
  platform: 'github',
  logFile: '/dist/renovate.log',
  onboarding: true,
  onboardingConfig: {
    extends: ['config:base'],
  },
  autodiscover: true,
  autodiscoverFilter: 'rvillane/renovate-gradle-test',
  requireConfig: true,
  automerge: false,
  extends: ['group:allNonMajor'],
  enabledManagers: ['gradle'],
  gradle: {
    'enabled': true
  },
  includeForks: true,
  rangeStrategy: 'pin',
  recreateClosed: true,
  stabilityDays: 7,
  prCreation:'not-pending',
  labels: [
    'renovate'
  ]
};
```

The target repo I forked from another issue in renovatebot/config-help https://github.com/rvillane/renovate-gradle-test

**Note**: I also tried using renovate/gradle:latest base image, but the container finished immediately with apparent action and no message printed on logs.

**Comment by rarkins** [comment]
If you need binaries like Gradle then you’ll need to run the full renovate image and not the slim

**Comment by rvillane** [comment]
it worked, thanks, perhaps that could be a bit more explicit on documentation.
