### ISSUE TITLE
Wrong .git/config

### ISSUE THREAD

**Issue by Djaler** [renovatebot/config-help#467]
**What Renovate type are you using?**

Self-hosten Renovate with GitLab.

**Describe the bug**

Renovate can't fetch repository after first launch.

```
ERROR: git fetch error (repository=lib/vuetify-utils)
       "err": {
         "message": "fatal: Couldn't find remote ref refs/heads/renovate/configure\n",
         "stack": "Error: fatal: Couldn't find remote ref refs/heads/renovate/configure\n\n    at /home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/promise.js:62:29\n    at Git.<anonymous> (/home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1549:20)\n    at Function.Git.fail (/home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1474:18)\n    at fail (/home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1432:20)\n    at /home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1441:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
```

**To Reproduce**

1. Clear renovate workdir (/tmp/renovate)
2. Run renovate
3. Run renovate again
4. See error in logs

**Additional context**

I found this in renovate workdir in `.git/config`:
```
...
[remote "origin"]
	url = ...
	fetch = +refs/heads/master:refs/remotes/origin/master
	fetch = +refs/heads/master:refs/remotes/origin/master
	fetch = +refs/heads/renovate/configure:refs/remotes/origin/renovate/configure
...
```

At first, here are two same entries for heads/master. And at second - here is explicit fetching for renovate/configure, that may be absent on remote

**Comment by rarkins** [comment]
I'm transferring this issue to config-help until we can determine if this really is a bug or caused by a misconfiguration. We can transfer back later if it's a bug.

Can you describe the exact but config you have, e.g. env config, CLI params, any `config.js`, etc? Please also capture the full debug logs for the runs to check for any suspicious messages at start or end of the run in particular.

BTW normally the behaviour should be to `git clone` every run and not `git fetch`. 

Did you configure `persistRepoData=true`?

Also, didn't Renovate recover from this error?

It should normally work like this:
- Repositories will be deleted after the run, and freshly cloned each time
- If the repository was not deleted, it attempts to fetch. If fetch fails, it empties the directory and clones instead

**Comment by Djaler** [comment]
I have `persistRepoData=true`, it's true.
And yes, looks like repository was cloned after fetch fail, it's cool. But I thing fetch shouldn't fail for that reason

**Comment by Djaler** [comment]
This is my config:
```
module.exports = {
    endpoint: ...,
    platform: `gitlab`,
    gitAuthor: ...,
    token: ...,
    autodiscover: true,
    persistRepoData: true,
    trustLevel: 'high',
    binarySource: 'global',
    logLevel: 'debug'
};

```

**Comment by rarkins** [comment]
After establishing that it continues and clones successfully, does the git fetch fail every time after that? i.e. it's fetch fail then clone, fetch fail then clone, etc? i.e. the failure cause - which may be the `.git/config` you identified - is repeatable?

**Comment by Djaler** [comment]
Yeah, `fetch` fail every time. Even if I run it manually from the work dir. So, looks like problem in generated `.git/config`
