### ISSUE TITLE
Configuring for custom NPM registry that requires auth

### ISSUE THREAD

**Issue by tuckbick** [renovatebot/config-help#507]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [ ] WhiteSource Renovate App
- [x] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [ ] GitHub.com
- [x] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

```
 INFO: lock file error (repository=Catalyst/my-app, dependencies=@homeaway/some-dependency, branch=renovate-homeaway-some-dependency-5.x)
       "cmd": "node /usr/src/app/node_modules/npm/bin/npm-cli.js",
       "args": "install --package-lock-only --no-audit",
       "err": {
         "killed": false,
         "code": 7,
         "signal": null,
         "cmd": "node /usr/src/app/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit",
         "stdout": "",
         "stderr": "Error: Failed to replace env in config: ${NPM_TOKEN}\n    at /usr/src/app/node_modules/npm/lib/config/core.js:415:13\n    at String.replace (<anonymous>)\n    at envReplace (/usr/src/app/node_modules/npm/lib/config/core.js:411:12)\n    at parseField (/usr/src/app/node_modules/npm/lib/config/core.js:389:7)\n    at /usr/src/app/node_modules/npm/lib/config/core.js:330:24\n    at Array.forEach (<anonymous>)\n    at Conf.add (/usr/src/app/node_modules/npm/lib/config/core.js:328:23)\n    at ConfigChain.addString (/usr/src/app/node_modules/npm/node_modules/config-chain/index.js:244:8)\n    at Conf.<anonymous> (/usr/src/app/node_modules/npm/lib/config/core.js:316:10)\n    at /usr/src/app/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16\n/usr/src/app/node_modules/npm/lib/npm.js:59\n      throw new Error('npm.load() required')\n      ^\n\nError: npm.load() required\n    at Object.get (/usr/src/app/node_modules/npm/lib/npm.js:59:13)\n    at process.errorHandler (/usr/src/app/node_modules/npm/lib/utils/error-handler.js:205:32)\n    at process.emit (events.js:198:13)\n    at process._fatalException (internal/bootstrap/node.js:496:27)\n",
         "message": "Command failed: node /usr/src/app/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\nError: Failed to replace env in config: ${NPM_TOKEN}\n    at /usr/src/app/node_modules/npm/lib/config/core.js:415:13\n    at String.replace (<anonymous>)\n    at envReplace (/usr/src/app/node_modules/npm/lib/config/core.js:411:12)\n    at parseField (/usr/src/app/node_modules/npm/lib/config/core.js:389:7)\n    at /usr/src/app/node_modules/npm/lib/config/core.js:330:24\n    at Array.forEach (<anonymous>)\n    at Conf.add (/usr/src/app/node_modules/npm/lib/config/core.js:328:23)\n    at ConfigChain.addString (/usr/src/app/node_modules/npm/node_modules/config-chain/index.js:244:8)\n    at Conf.<anonymous> (/usr/src/app/node_modules/npm/lib/config/core.js:316:10)\n    at /usr/src/app/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16\n/usr/src/app/node_modules/npm/lib/npm.js:59\n      throw new Error('npm.load() required')\n      ^\n\nError: npm.load() required\n    at Object.get (/usr/src/app/node_modules/npm/lib/npm.js:59:13)\n    at process.errorHandler (/usr/src/app/node_modules/npm/lib/utils/error-handler.js:205:32)\n    at process.emit (events.js:198:13)\n    at process._fatalException (internal/bootstrap/node.js:496:27)\n",
         "stack": "Error: Command failed: node /usr/src/app/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\nError: Failed to replace env in config: ${NPM_TOKEN}\n    at /usr/src/app/node_modules/npm/lib/config/core.js:415:13\n    at String.replace (<anonymous>)\n    at envReplace (/usr/src/app/node_modules/npm/lib/config/core.js:411:12)\n    at parseField (/usr/src/app/node_modules/npm/lib/config/core.js:389:7)\n    at /usr/src/app/node_modules/npm/lib/config/core.js:330:24\n    at Array.forEach (<anonymous>)\n    at Conf.add (/usr/src/app/node_modules/npm/lib/config/core.js:328:23)\n    at ConfigChain.addString (/usr/src/app/node_modules/npm/node_modules/config-chain/index.js:244:8)\n    at Conf.<anonymous> (/usr/src/app/node_modules/npm/lib/config/core.js:316:10)\n    at /usr/src/app/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16\n/usr/src/app/node_modules/npm/lib/npm.js:59\n      throw new Error('npm.load() required')\n      ^\n\nError: npm.load() required\n    at Object.get (/usr/src/app/node_modules/npm/lib/npm.js:59:13)\n    at process.errorHandler (/usr/src/app/node_modules/npm/lib/utils/error-handler.js:205:32)\n    at process.emit (events.js:198:13)\n    at process._fatalException (internal/bootstrap/node.js:496:27)\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       },
       "stdout": "",
       "stderr": "",
       "type": "npm"
```

The above error, but more readable:
```
Error: Command failed: node /usr/src/app/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /usr/src/app/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/usr/src/app/node_modules/npm/lib/config/core.js:411:12)
    at parseField (/usr/src/app/node_modules/npm/lib/config/core.js:389:7)
    at /usr/src/app/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/usr/src/app/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (/usr/src/app/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/src/app/node_modules/npm/lib/config/core.js:316:10)
    at /usr/src/app/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
/usr/src/app/node_modules/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/src/app/node_modules/npm/lib/npm.js:59:13)
    at process.errorHandler (/usr/src/app/node_modules/npm/lib/utils/error-handler.js:205:32)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

### What would you like to do?

We would like Renovate to be able to update `package-lock.json` files. PR's are created to bump the dependency, but creation of the `package-lock.json` artifact results in the above error.

Renovate `config.js`:
```
module.exports = {
    "npmrc": "registry=https://npm.custom-registry.com/artifactory/\n//npm.custom-registry.com/artifactory/:_authToken=${NPM_TOKEN}",
    "ignoreNpmrcFile": true
};
```

Additionally, `NPM_TOKEN` is getting set before starting Renovate.

**Comment by tuckbick** [comment]
Also - the value that I'm using for for `NPM_TOKEN` is too long to be encrypted via https://renovatebot.com/encrypt.

**Comment by rarkins** [comment]
By default Renovate does not pass the full env to child_process when it calls out to `npm` and other scripts. To pass the full env, you need to configure `trustLevel=high` in your bot config.

**Comment by rarkins** [comment]
Possibly this would work too:

```
module.exports = {
    "npmrc": "registry=https://npm.custom-registry.com/artifactory/\n//npm.custom-registry.com/artifactory/:_authToken=${NPM_TOKEN}",
    "npmToken": process.env.NPM_TOKEN,
    "ignoreNpmrcFile": true
};
```

**Comment by tuckbick** [comment]
Those suggestions make sense. Thank you!

For the second one seems like the most convenient, so I'd like to use that method, but I'm seeing spots in the logs where `npmToken` is not redacted like it is in most other places:

<img width="435" alt="Screen Shot 2020-01-28 at 9 10 13 AM" src="https://user-images.githubusercontent.com/230995/73276435-4bcc0c00-41ae-11ea-811f-7dfe0c3263c4.png">

**Comment by tuckbick** [comment]
It turns out neither of these solutions actually worked for me, both leading me to the same error.
I've worked around it for now by setting up an `.npmrc` at runtime, resulting in a file that contains `_auth = <some-token>`.

**Comment by rarkins** [comment]
> The second one seems like the most convenient method, so I'd like to use that, but I'm seeing spots in the logs where `npmToken` is not redacted like it is in most other places:

We don't go to particular effort to redact things at trace level. 

> It turns out neither of these solutions actually worked for me

I'm really surprised if the `trustLevel` solution didn't work, because it passes through env variables unfiltered. i.e. if `NPM_TOKEN` is in the env you pass to Renovate then it should be in the env passed to `npm`/`yarn`.

**Comment by tuckbick** [comment]
Thanks for your help @rarkins!
