### ISSUE TITLE
repository-changed error

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#567]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Repository started
{
  "renovateVersion": "19.167.0"
}
INFO: Repository has changed during renovation - aborting
INFO: Repository finished
```

### What would you like to do?

I'm seeing all the recent jobs in a repository showing this output. I am noticing that the master issue in that repository is out of date and doesn't match the PRs that are open, for instance, but I'm not sure if it's related. The log output suggests that Renovate is not completing successfully.

![image](https://user-images.githubusercontent.com/20181/76303981-dbdb9600-62c2-11ea-89cc-83865762b981.png)

**Comment by rarkins** [comment]
What do the DEBUG messages say prior to the "Repository has changed"?

Master issue being out of date is to be expected as normally this is meant to be a transient error and we don't want Renovate to update the issue with temporarily incorrect information. However in this case clearly something else is going wrong.

**Comment by simoneb** [comment]
Ok I see what's happening here, the GitHub API is returning an error. See below.

Note that these are errors but logged as DEBUG messages, which doesn't really help troubleshooting. This log is from a few minutes ago.

```
DEBUG: Updating renovate/stability-days status check state to pending(branch="renovate/dayjs-1.x")
DEBUG: Setting branch status(branch="renovate/dayjs-1.x")
{
  "context": "renovate/stability-days",
  "state": "pending"
}
DEBUG: 422 Error thrown from GitHub(branch="renovate/dayjs-1.x")
{
  "err": {
    "name": "HTTPError",
    "hostname": "api.github.com",
    "method": "POST",
    "path": "/repos/[org]/[repo]/statuses/72f2ffb0ca333c027ff7712d8cc06efdc9957f0e",
    "protocol": "https:",
    "url": "https://api.github.com/repos/[org]/[repo]/statuses/72f2ffb0ca333c027ff7712d8cc06efdc9957f0e",
    "gotOptions": {
      "path": "/repos/[org]/[repo]/statuses/72f2ffb0ca333c027ff7712d8cc06efdc9957f0e",
      "protocol": "https:",
      "hostname": "api.github.com",
      "hash": "",
      "search": "",
      "pathname": "/repos/[org]/[repo]/statuses/72f2ffb0ca333c027ff7712d8cc06efdc9957f0e",
      "href": "https://api.github.com/repos/[org]/[repo]/statuses/72f2ffb0ca333c027ff7712d8cc06efdc9957f0e",
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept": "application/vnd.github.machine-man-preview+json",
        "accept-encoding": "gzip, deflate",
        "content-type": "application/json",
        "authorization": "** redacted **",
        "content-length": 146
      },
      "hooks": {
        "beforeError": [],
        "init": [],
        "beforeRequest": [],
        "beforeRedirect": [],
        "beforeRetry": [],
        "afterResponse": []
      },
      "retry": {
        "methods": {},
        "statusCodes": {},
        "errorCodes": {}
      },
      "decompress": true,
      "throwHttpErrors": true,
      "followRedirect": true,
      "stream": false,
      "form": false,
      "json": true,
      "cache": false,
      "useElectronNet": false,
      "hostType": "github",
      "baseUrl": "https://api.github.com/",
      "body": "{\"description\":\"Updates have not met stability days requirement\",\"context\":\"renovate/stability-days\",\"target_url\":\"https://docs.renovatebot.com/\"}",
      "method": "POST"
    },
    "statusCode": 422,
    "statusMessage": "Unprocessable Entity",
    "headers": {
      "date": "Tue, 10 Mar 2020 10:34:19 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "228",
      "connection": "close",
      "server": "GitHub.com",
      "status": "422 Unprocessable Entity",
      "x-ratelimit-limit": "12500",
      "x-ratelimit-remaining": "12284",
      "x-ratelimit-reset": "1583838879",
      "x-github-media-type": "github.machine-man-preview; format=json",
      "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
      "access-control-allow-origin": "*",
      "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
      "x-frame-options": "deny",
      "x-content-type-options": "nosniff",
      "x-xss-protection": "1; mode=block",
      "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
      "content-security-policy": "default-src 'none'",
      "vary": "Accept-Encoding, Accept, X-Requested-With",
      "x-github-request-id": "E964:9F71:B93FD3:DED281:5E676D2B"
    },
    "body": {
      "message": "Validation Failed",
      "errors": [
        {
          "resource": "Status",
          "code": "custom",
          "field": "state",
          "message": "state is not included in the list"
        }
      ],
      "documentation_url": "https://developer.github.com/v3/repos/statuses/#create-a-status"
    },
    "message": "Response code 422 (Unprocessable Entity)",
    "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at EventEmitter. (/home/ubuntu/renovateapp/node_modules/got/source/as-promise.js:74:19)\n    at runMicrotasks ()\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  }
}
DEBUG: Caught error setting branch status - aborting(branch="renovate/dayjs-1.x")
{
  "err": {
    "message": "platform-failure",
    "stack": "Error: platform-failure\n    at dispatchError (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/gh-got-wrapper.js:77:15)\n    at get (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/github/gh-got-wrapper.js:146:9)\n    at runMicrotasks ()\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  }
}
DEBUG: Passing repository-changed error up(branch="renovate/dayjs-1.x")
INFO: Repository has changed during renovation - aborting
INFO: Repository finished
```

**Comment by rarkins** [comment]
If you want to know what's going on, look at INFO. If you want to know what's going wrong, look at DEBUG.
