### ISSUE TITLE
Renovate job fails with "yarn: not found"

### ISSUE THREAD

**Issue by reppiee** [renovatebot/config-help#579]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Generating yarn.lock for . (repository=example/team/core, branch=renovate/pin-dependencies)
DEBUG: Spawning yarn install to create /home/ubuntu/repos/gitlab/example/team/core/yarn.lock (repository=example/team/core, branch=renovate/pin-dependencies)
DEBUG: No locally installed yarn found (repository=example/team/core, branch=renovate/pin-dependencies)
DEBUG: Could not find globally nested yarn (repository=example/team/core, branch=renovate/pin-dependencies)
 WARN: Could not find globally installed yarn (repository=example/team/core, branch=renovate/pin-dependencies)
DEBUG: Using yarn: yarn (repository=example/team/core, branch=renovate/pin-dependencies)
DEBUG: Executing command (repository=example/team/core, branch=renovate/pin-dependencies)
       "command": "yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879"
DEBUG: lock file error (repository=example/team/core, branch=renovate/pin-dependencies)
       "cmd": "yarn",
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
         "stdout": "",
         "stderr": "/bin/sh: 1: yarn: not found\n",
         "message": "Command failed: yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: 1: yarn: not found\n",
         "stack": "Error: Command failed: yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: 1: yarn: not found\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:311:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)"
       },
       "stdout": "",
       "stderr": "",
       "type": "yarn"
```

### What would you like to do?

I want to run Renovate to upgrade our Javascript dependencies. 

The GitLab CI job it set up as follows:
```
renovate:
  image: 
    name: renovate/renovate
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
    - export RENOVATE_TOKEN=$CI_BOT_TOKEN
    - export LOG_LEVEL=debug
    - export GITHUB_COM_TOKEN=xxxxxx
  stage: renovate
  script:
    - node /usr/src/app/dist/renovate.js $(cat repositories.txt | xargs)
    - rm -rf /home/ubuntu/{cache,repos}
```

It's currently creating Merge Requests successfully, but fails to update the `yarn.lock` file because of the error mentioned in the logfile.

I've tried this with `binarySource` set to both "docker" and "auto" in the Renovate config file, but it throws the same error in both cases.

**Comment by viceice** [comment]
which version of renovate are you using? for the full image you shouldn't need to set `binarySource`, because all tools are installed globally

**Comment by reppiee** [comment]
Using renovate:latest from DockerHub, the logs are from version `19.175.3`

The reason I've set `binarySource` in the config is because we also have ruby dependencies we want to scan/update and as I understood renovate does not come with ruby installed globally (found that out when the job was failing due to an error related to that).

**Comment by reppiee** [comment]
I've also tried a run without `binarySource` set, which gives the same error:

```
DEBUG: Generating yarn.lock for . (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
DEBUG: Spawning yarn install to create /home/ubuntu/repos/gitlab/example/team/core/yarn.lock (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
DEBUG: No locally installed yarn found (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
DEBUG: Could not find globally nested yarn (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
 WARN: Could not find globally installed yarn (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
DEBUG: Using yarn: yarn (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
DEBUG: Executing command (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
       "command": "yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879"
DEBUG: lock file error (repository=example/team/core, branch=renovate/stylelint-declaration-use-variable-1.x)
       "cmd": "yarn",
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
         "stdout": "",
         "stderr": "/bin/sh: 1: yarn: not found\n",
         "message": "Command failed: yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: 1: yarn: not found\n",
```

**Comment by viceice** [comment]
your config seems to be wrong

```
❯ docker run --rm -it --entrypoint="" renovate/renovate yarn --version
1.22.4
❯ docker run --rm -it --entrypoint="" renovate/renovate ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

Try setting `binrarySource='global'`

**Comment by viceice** [comment]
Maybe there is something wrong with your `PATH`.

It should be like this:
```
❯ docker run --rm -it --entrypoint="" renovate/renovate bash
ubuntu@f848a471ff28:/usr/src/app$ echo $PATH
/home/ubuntu/.yarn/bin:/home/ubuntu/.config/yarn/global/node_modules/.bin:/home/ubuntu/.poetry/bin:/home/ubuntu/.local/bin:/home/ubuntu/.cargo/bin:/go/bin:/usr/local/go/bin:/home/ubuntu/.y
arn/bin:/home/ubuntu/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/elixir-1.8.2/bin
```

So please check this.

**Comment by reppiee** [comment]
Thanks for the fast responses! I tried setting `binarySource: "auto"` and got the following two errors, one for `yarn` and one for `bundler`:

```
DEBUG: lock file error (repository=example/team/core, branch=renovate/textarea-caret-3.x)
        "cmd": "yarn",
        "err": {
          "killed": false,
          "code": 127,
          "signal": null,
          "cmd": "yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
          "stdout": "",
          "stderr": "/bin/sh: 1: yarn: not found\n",
          "message": "Command failed: yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: 1: yarn: not found\n",
          "stack": "Error: Command failed: yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: 1: yarn: not found\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:311:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)"
        },
        "stdout": "",
        "stderr": "",
        "type": "yarn"
        
DEBUG: Executing command (repository=example/team/core, branch=renovate/approvals-0.x)
       "command": "bundle lock --update approvals"
 WARN: Gemfile.lock update failed due to unknown reason - skipping branch (repository=example/team/core, branch=renovate/approvals-0.x)
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "bundle lock --update approvals",
         "stdout": "",
         "stderr": "/bin/sh: 1: bundle: not found\n",
         "message": "Command failed: bundle lock --update approvals\n/bin/sh: 1: bundle: not found\n",
         "stack": "Error: Command failed: bundle lock --update approvals\n/bin/sh: 1: bundle: not found\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:311:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:311:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at Pipe.<anonymous> (net.js:668:12)"
       }  
```

And the result from `echo $PATH`:
```
$ echo $PATH
 /home/ubuntu/.poetry/bin:/home/ubuntu/.local/bin:/home/ubuntu/.cargo/bin:/go/bin:/usr/local/go/bin:/home/ubuntu/.yarn/bin:/home/ubuntu/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/elixir-1.8.2/bin
```

My config is currently like this:

**Renovate config.js**
```
module.exports = {
  platform: "gitlab",
  baseBranches: ["renovate-experimenting"],
  labels: ["renovate"],
  extends: ["config:base"], 
  pruneStaleBranches: false,
  binarySource: "global",
  baseDir: "/home/ubuntu"
};
```

**renovate.json in repository**
```
{
  "js": {
    "prHourlyLimit": 1,
    "packageRules": [
      {
        "updateTypes": ["minor", "patch", "pin", "digest"]
      }
    ]
  },
  "ruby": {
    "enabledManagers": ["bundler"],
    "prHourlyLimit": 1,
    "recreateClosed": true,
    "packageRules": [
      {
        "updateTypes": ["minor", "patch", "pin", "digest"]
      }
    ]
  }
}
```

**Comment by viceice** [comment]
can you please run this pipeline:
```yml
renovate:
  image: 
    name: renovate/renovate
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
    - export RENOVATE_TOKEN=$CI_BOT_TOKEN
    - export LOG_LEVEL=debug
    - export GITHUB_COM_TOKEN=xxxxxx
    - export RENOVATE_BINARY_SOURCE=global
  stage: renovate
  script:
    - node /usr/src/app/dist/renovate.js --version
    - yarn --version || echo 'missing yarn'
    - ruby --version || echo 'missing ruby'
    - gem --version || echo 'missing gem'
    - gem install bundler || echo 'missing gem'
    - node /usr/src/app/dist/renovate.js $(cat repositories.txt | xargs)
    - rm -rf /home/ubuntu/{cache,repos}
```

**Comment by reppiee** [comment]
Yep ran that, this was the output in the job:

```
DEBUG: Checking for config file in /builds/hackerone/engineering_and_product/renovate/config
19.176.1
$ yarn --version || echo 'missing yarn'
/bin/bash: line 106: yarn: command not found
missing yarn
$ ruby --version || echo 'missing ruby'
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
$ gem --version || echo 'error installing bundler'
2.7.6
$ gem install bundler || echo 'missing gem'
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
missing gem
```

**Comment by viceice** [comment]
ok, one more please

```yml
renovate:
  image: 
    name: renovate/renovate
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
    - export RENOVATE_TOKEN=$CI_BOT_TOKEN
    - export LOG_LEVEL=debug
    - export GITHUB_COM_TOKEN=xxxxxx
    - export RENOVATE_BINARY_SOURCE=global
  stage: renovate
  script:
    - echo $PATH
    - which yarn
    - node /usr/src/app/dist/renovate.js --version
    - which yarn
    - echo $PATH
```

**Comment by reppiee** [comment]
Certainly! Thanks for taking the time to help. The `which yarn` commands fails in this case:

```
 $ echo $PATH
/home/ubuntu/.poetry/bin:/home/ubuntu/.local/bin:/home/ubuntu/.cargo/bin:/go/bin:/usr/local/go/bin:/home/ubuntu/.yarn/bin:/home/ubuntu/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/elixir-1.8.2/bin
 $ which yarn
 ERROR: Job failed: exit code 1
```

**Comment by viceice** [comment]
Please run:
```yml
renovate:
  image: 
    name: renovate/renovate
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
    - export RENOVATE_TOKEN=$CI_BOT_TOKEN
    - export LOG_LEVEL=debug
    - export GITHUB_COM_TOKEN=xxxxxx
    - export RENOVATE_BINARY_SOURCE=global
  stage: renovate
  script:
    - ls -la /home/ubuntu/
```

Can you please share your  `config.toml` from your gitlab runner?
I would like to know the volumes mounted to containers.

**Comment by reppiee** [comment]
```
 $ ls -la /home/ubuntu/
 total 32
 drwxr-xr-x 5 ubuntu ubuntu 4096 Mar 15 04:20 .
 drwxr-xr-x 1 root   root   4096 Mar 17 13:54 ..
 -rw-r--r-- 1 ubuntu ubuntu  220 Apr  4  2018 .bash_logout
 -rw-r--r-- 1 ubuntu ubuntu 3771 Apr  4  2018 .bashrc
 drwx------ 2 ubuntu ubuntu 4096 Mar 15 04:20 .cache
 drwx------ 3 ubuntu ubuntu 4096 Mar 15 04:20 .gnupg
 -rw-r--r-- 1 ubuntu ubuntu  807 Apr  4  2018 .profile
 drwx------ 2 ubuntu ubuntu 4096 Mar 15 04:20 .ssh
 -rw-r--r-- 1 ubuntu ubuntu    0 Mar 15 04:20 .sudo_as_admin_successful
 Job succeeded
```

These are the runner volume related settings from our gitlab runner ansible role:
```
volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache", "/home/ubuntu:/home/ubuntu"]
```

**Comment by reppiee** [comment]
For context, the `baseDir: "/home/ubuntu"` and volume mounts were a workaround we implemented when we switched to `binarySource: "docker"` to get bundler to work, but ran into permission errors. I don't know the exact specifics of those errors and why the workaround worked.

But if I understand you correctly, `bundler` should work with `binarySource: "global"` as well? In which case I could revert that workaround and use the default `baseDir` if you think that might help.

**Comment by viceice** [comment]
yes, remove home mount. use `renovate/renovate:slim` and `binarySource: "docker"`. That's the way i use it on my own gitlab instance

**Comment by reppiee** [comment]
Okay, I've gone back to these settings now:
```
module.exports = {
  platform: "gitlab",
  baseBranches: ["renovate-experimenting"],
  labels: ["renovate"],
  extends: ["config:base"], 
  pruneStaleBranches: false,
  binarySource: "docker"
};
```

Unfortunately the error remains the same:
```
DEBUG: lock file error (repository=example/team/core, branch=renovate/browsertime-8.x)
        "cmd": "yarn",
        "err": {
          "killed": false,
          "code": 127,
          "signal": null,
          "cmd": "yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
          "stdout": "",
          "stderr": "/bin/sh: 1: yarn: not found\n",
          "message": "Command failed: yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: 1: yarn: not found\n",
          "stack": "Error: Command failed: yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: 1: yarn: not found\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:311:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:311:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at Pipe.<anonymous> (net.js:668:12)"
        },
        "stdout": "",
        "stderr": "",
        "type": "yarn"
```

**Comment by viceice** [comment]
```yml
renovate:
  image: 
    name: renovate/renovate:slim
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
    - export RENOVATE_TOKEN=$CI_BOT_TOKEN
    - export LOG_LEVEL=debug
    - export GITHUB_COM_TOKEN=xxxxxx
    - export RENOVATE_BINARY_SOURCE=docker
  stage: renovate
  script:
    - ls -la /home/ubuntu/
    - which yarn || 'Missing yarn'
    - node /usr/src/app/dist/renovate.js $(cat repositories.txt | xargs)
```

**Comment by reppiee** [comment]
```
$ ls -la /home/ubuntu/
 total 32
 drwxr-xr-x 5 ubuntu ubuntu 4096 Mar 15 04:20 .
 drwxr-xr-x 1 root   root   4096 Mar 17 13:54 ..
 -rw-r--r-- 1 ubuntu ubuntu  220 Apr  4  2018 .bash_logout
 -rw-r--r-- 1 ubuntu ubuntu 3771 Apr  4  2018 .bashrc
 drwx------ 2 ubuntu ubuntu 4096 Mar 15 04:20 .cache
 drwx------ 3 ubuntu ubuntu 4096 Mar 15 04:20 .gnupg
 -rw-r--r-- 1 ubuntu ubuntu  807 Apr  4  2018 .profile
 drwx------ 2 ubuntu ubuntu 4096 Mar 15 04:20 .ssh
 -rw-r--r-- 1 ubuntu ubuntu    0 Mar 15 04:20 .sudo_as_admin_successful
 $ which yarn || 'Missing yarn'
 /bin/bash: line 106: Missing yarn: command not found
 ERROR: Job failed: exit code 1
```

**Comment by reppiee** [comment]
Correct me if I'm wrong, but if I set `binarySource` to `docker`, that means it should be running all the yarn install/update commands inside a docker container right? 

So the container in which we execute the `which yarn` here would not need `yarn` itself?

**Comment by viceice** [comment]
have you removed the home mount point from gitlab runner? If you mount the home volume it will break renovate

**Comment by reppiee** [comment]
Oh, no I have not removed the mount point - I've only removed the `baseDir` config option.

**Comment by viceice** [comment]
in the renovate/yarn image yarn is located in /home/ubuntu (other images use that too), so do not mount this

**Comment by reppiee** [comment]
👍 Cool! That change will take a little longer as I have to talk to someone in the team to remove that. Will update here once that's been done, thanks!

**Comment by reppiee** [comment]
We removed the `/home/ubuntu` volume mount, and the following job ran with this as output:

```
 $ which yarn || 'Missing yarn'
 /home/ubuntu/.yarn/bin/yarn
```

And the run was successful! `yarn.lock` updated successfully too. Thanks so much for the help!
