### ISSUE TITLE
Configuration with private artifactory

### ISSUE THREAD

**Issue by mmaeller** [renovatebot/config-help#592]
### Which Renovate are you using?
Renovate docker image 19.156.0

Other (please write below)

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
 WARN: Error getting docker image tags (repository=backend/myproject)
       "registry": "https://artifactoryDomain",
       "dockerRepository": "backend-docker/openjdk",
       "err": {
         "name": "HTTPError",
         "host": "artifactoryDomain",
         "hostname": "artifactoryDomain",
         "method": "GET",
         "path": "/v2/backend-docker/openjdk/tags/list?n=10000",
         "protocol": "https:",
         "url": "https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000",
         "gotOptions": {
           "path": "/v2/backend-docker/openjdk/tags/list?n=10000",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "artifactoryDomain",
           "port": null,
           "hostname": "artifactoryDomain",
           "hash": null,
           "search": "?n=10000",
           "pathname": "/v2/backend-docker/openjdk/tags/list",
           "href": "https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "authorization": "** redacted **",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx/1.17.7",
           "date": "Mon, 30 Mar 2020 13:22:58 GMT",
           "content-type": "application/json",
           "transfer-encoding": "chunked",
           "connection": "close",
           "vary": "Accept-Encoding",
           "x-artifactory-id": "qwertz",
           "docker-distribution-api-version": "registry/2.0",
           "strict-transport-security": "max-age=15724800; includeSubDomains",
           "content-encoding": "gzip"
         },
         "body": {
           "errors": [
             {
               "code": "NAME_UNKNOWN",
               "message": "Repository name not known to registry.",
               "detail": {"name": "openjdk"}
             }
           ]
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/usr/local/lib/node_modules/renovate/node_modules/got/source/as-promise.js:74:19)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
       }
```

### What would you like to do?
The gitlab project `myproject` in gitlab group backend contains a Dockerfile.
This file is being scanned, but the tags cannot be resolved since the URL is not built properly.
It should read https://artifactoryDomain/v2/backend-docker/library/openjdk/tags/list?n=10000 instead of https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000, since our artifactory has grouped repositories.

Is there any configuration option to fix this?

I already tried 

```
  "hostRules": [
    {
      "hostType": "docker",
      "baseUrl": "https://artifactoryDomain/backend-docker"
    }
  ],
```
but got the same result.
For me it seems like https://github.com/renovatebot/renovate/blob/master/lib/datasource/docker/index.ts#L372 is a poor condition in this case, because the repository reads `backend-docker/openjdk`.

**Comment by rarkins** [comment]
What is the full extraction of it? Look for the "packageFiles with updates" debug message and locate this dependency's object in full.

**Comment by mmaeller** [comment]
```
    "dockerfile": [
        {
            "packageFile": "Dockerfile",
            "manager": "dockerfile",
            "deps": [
                {
                    "depName": "artifactoryDomain/backend-docker/openjdk",
                    "currentFrom": "artifactoryDomain/backend-docker/openjdk:12-alpine",
                    "currentDepTag": "artifactoryDomain/backend-docker/openjdk:12-alpine",
                    "currentValue": "12-alpine",
                    "datasource": "docker",
                    "lineNumber": 0,
                    "fromPrefix": "FROM",
                    "fromSuffix": "",
                    "depType": "final",
                    "updates": [],
                    "warnings": [
                        {
                            "updateType": "warning",
                            "message": "Failed to look up dependency artifactoryDomain/backend-docker/openjdk"
                        }
                    ]
                }
            ]
        }
    ],```

**Comment by rarkins** [comment]
Is `artifactoryDomain` a full hostname, e.g. `artifactory.company.com` ? Also does it require authentication and if so then have you configured any `hostRules` entry for it?

**Comment by mmaeller** [comment]
Yes, it's that kind of.
`artifactoryDomain/backend-docker` is equal to `artifactory.company.com/backend-docker`
My hostRules are simple:
```
  "hostRules": [
    {
      "hostType": "docker",
      "baseUrl": "https://artifactory.company.com/backend-docker",
      "username": "myuser",
      "password": "mypass"
    }
  ],
```
It doesn't make a difference whether I add the credentials or not.

**Comment by rarkins** [comment]
Now earlier you wrote:

> It should read https://artifactoryDomain/v2/backend-docker/library/openjdk/tags/list?n=10000 instead of https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000, since our artifactory has grouped repositories.

But it does seem like it tried that in the logs. The url it shows was 
`https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000` and that returned 404. It only fell back to trying `library/*` when the first one didn't work.

Can you use `curl` to determine the exact auth headers you need to pass to that URL to get it to succeed?

**Comment by mmaeller** [comment]
No, the logs contain only a request to https://artifactorydomain/v2/backend-docker/openjdk/tags/list?n=10000
The retry with prefixed `library/` hasn't been executed.

Shouldn't the dockerRepository only be `openjdk` and not `backend-docker/openjdk`?
`backend-docker` is just the internal artifactory repository group.

```
{
    "name": "renovate",
    "hostname": "MacBook-Pro.local",
    "pid": 33921,
    "level": 40,
    "logContext": "5RlREzHz-",
    "repository": "matmae/test",
    "registry": "https://artifactory.company.com",
    "dockerRepository": "backend-docker/openjdk",
    "err": {
        "name": "HTTPError",
        "host": "artifactory.company.com",
        "hostname": "artifactory.company.com",
        "method": "GET",
        "path": "/v2/backend-docker/openjdk/tags/list?n=10000",
        "protocol": "https:",
        "url": "https://artifactory.company.com/v2/backend-docker/openjdk/tags/list?n=10000",
        "gotOptions": {
            "path": "/v2/backend-docker/openjdk/tags/list?n=10000",
            "protocol": "https:",
            "slashes": true,
            "auth": null,
            "host": "artifactory.company.com",
            "port": null,
            "hostname": "artifactory.company.com",
            "hash": null,
            "search": "?n=10000",
            "pathname": "/v2/backend-docker/openjdk/tags/list",
            "href": "https://artifactory.company.com/v2/backend-docker/openjdk/tags/list?n=10000",
            "headers": {
                "user-agent": "https://github.com/renovatebot/renovate",
                "authorization": "** redacted **",
                "accept": "application/json",
                "accept-encoding": "gzip, deflate"
            },
            "hooks": {
                "beforeError": [],
                "init": [],
                "beforeRequest": [],
                "beforeRedirect": [],
                "beforeRetry": [],
                "afterResponse": []
            },
            "retry": {
                "methods": {},
                "statusCodes": {},
                "errorCodes": {}
            },
            "decompress": true,
            "throwHttpErrors": true,
            "followRedirect": true,
            "stream": false,
            "form": false,
            "json": true,
            "cache": false,
            "useElectronNet": false,
            "method": "GET",
            "gotTimeout": {
                "request": 60000
            }
        },
        "statusCode": 404,
        "statusMessage": "Not Found",
        "headers": {
            "server": "nginx/1.17.7",
            "date": "Tue, 31 Mar 2020 06:55:52 GMT",
            "content-type": "application/json",
            "transfer-encoding": "chunked",
            "connection": "close",
            "vary": "Accept-Encoding",
            "x-artifactory-id": "asd",
            "docker-distribution-api-version": "registry/2.0",
            "strict-transport-security": "max-age=15724800; includeSubDomains",
            "content-encoding": "gzip"
        },
        "body": {
            "errors": [
                {
                    "code": "NAME_UNKNOWN",
                    "message": "Repository name not known to registry.",
                    "detail": {
                        "name": "openjdk"
                    }
                }
            ]
        },
        "message": "Response code 404 (Not Found)",
        "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/renovate/node_modules/got/source/as-promise.js:74:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    },
    "msg": "Error getting docker image tags",
    "time": "2020-03-31T06:55:19.842Z",
    "v": 0
}
`
``

**Comment by rarkins** [comment]
If you test with `FROM artifactoryDomain/backend-docker/library/openjdk:12-alpine` then does it look up successfully?

**Comment by rarkins** [comment]
Please do this:
- Create a new repository
- Have a single Dockerfile with a single `FROM` matching `
FROM artifactoryDomain/backend-docker/openjdk:12-alpine`
- Run Renovate against that repository with LOG_LEVEL=debug in env and save the output
- Redact then post the output

**Comment by mmaeller** [comment]
Yes, with prefixed `library/` it's working.
Here the debug output of the run without `library/` and just single Dockerfile: [renovate.log](https://github.com/renovatebot/config-help/files/4409139/renovate.log)

**Comment by mmaeller** [comment]
Hi,

Do you have any further recommendations?

Kind regards

**Comment by rarkins** [comment]
It seems like a solvable problem, but I'm not sure how. I'm wondering if somehow Renovate should be able to know that `FROM artifactoryDomain/backend-docker/openjdk:12-alpine` means a registry of `artifactoryDomain/backend-docker` instead of `artifactoryDomain` alone, or if it has to just try/fail/try again.
