### ISSUE TITLE
Cannot find preset's package (group:telus-tdsMonorepo)

### ISSUE THREAD

**Issue by screendriver** [renovatebot/config-help#625]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```sh
 FATAL: Fatal error: config-validation
        "err": {
          "validationError": "Cannot find preset's package (group:telus-tdsMonorepo). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
          "message": "config-validation",
          "stack": "Error: config-validation\n    at resolveConfigPresets (/builds/tooling/renovate/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
        }
  INFO: Renovate is exiting with a non-zero code due to the following logged errors
        "loggerErrors": [
          {
            "name": "renovate",
            "level": 60,
            "logContext": "WRT5bG7Tf",
            "err": {
              "validationError": "Cannot find preset's package (group:telus-tdsMonorepo). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
              "message": "config-validation",
              "stack": "Error: config-validation\n    at resolveConfigPresets (/builds/tooling/renovate/node_modules/renovate/dist/config/presets/index.js:203:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
            },
            "msg": "Fatal error: config-validation"
          }
        ]
```

### What would you like to do?

I'm using `renovate-config-validator` to validate my config file. Since yesterday  (when Renovate updated itself to `v19.221.0`) I get this error.

**Comment by viceice** [comment]
Should be fixed in [19.221.1](https://github.com/renovatebot/renovate/releases/tag/19.221.1)

**Comment by screendriver** [comment]
With the latest version `v19.221.2` I'm getting

```sh
 FATAL: Fatal error: platform-failure
        "err": {
          "message": "platform-failure",
          "stack": "Error: platform-failure\n    at fetchJSONFile (/builds/tooling/renovate/node_modules/renovate/dist/config/presets/github.js:31:19)\n    at getPresetFromEndpoint (/builds/tooling/renovate/node_modules/renovate/dist/config/presets/github.js:80:29)\n    at Object.getPreset (/builds/tooling/renovate/node_modules/renovate/dist/config/presets/github.js:94:12)\n    at getPreset (/builds/tooling/renovate/node_modules/renovate/dist/config/presets/index.js:141:58)\n    at Object.resolveConfigPresets (/builds/tooling/renovate/node_modules/renovate/dist/config/presets/index.js:194:43)\n    at Object.parseConfigs (/builds/tooling/renovate/node_modules/renovate/dist/config/index.js:48:40)\n    at async Object.start (/builds/tooling/renovate/node_modules/renovate/dist/workers/global/index.js:62:22)\n    at async /builds/tooling/renovate/node_modules/renovate/dist/renovate.js:16:24"
        }
```

**Comment by screendriver** [comment]
Fixed with one of the latest updates
