### ISSUE TITLE
Gitlab: PR creation failure for node (docker) deps

### ISSUE THREAD

**Issue by tyronedd** [renovatebot/config-help#650]
First of all, thank you for this amazing tool!

### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab.com

### Configuration

```javascript
const baseDir = process.env.CI_PROJECT_DIR;

module.exports = {
    logLevel: 'debug',
    baseDir,
    recreateClosed: true,
    extends: [
        "config:base",
        ":semanticCommitTypeAll(build)"
    ],
    endpoint: "https://gitlab.com/api/v4/",
    platform: "gitlab",
    gitLabAutomerge: true,
    assignees: [
        "tmeijn"
    ],
    baseBranches: [
        "feature/renovate-testing"
    ],
    labels: [
        "CI/CD",
        "Renovate"
    ],
    // No limit on creation of Merge Requests.
    prHourlyLimit: 0,
    prConcurrentLimit: 20,
    // rebaseWhen: "behind-base-branch",
    // persistRepoData: true,
    //Auto-merge config,
    // allow patch dependencies to be auto-merged
    packageRules: [
        {
            managers: ["npm"],
            depTypeList: [
                "dependencies"
            ],
            extends: [
                ":automergePatch"
            ],
        },
        {
            managers: ["npm"],
            depTypeList: ["devDependencies"],
            extends: [":automergeMinor"],
            semanticCommitScope: "devDeps"
        }
    ]
};

```

### Have you checked the logs? Don't forget to include them if relevant

Full log [here on Pastebin.com](https://pastebin.com/tqB2JZmu)

relevant part:
```
DEBUG: processBranch with 2 upgrades (repository=_COMPANY_/_PROJECT_/services/client, dependencies=node,@types/node, branch=renovate/node-12.x)
DEBUG: Setting baseBranch to feature/renovate-testing (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Setting baseBranch to feature/renovate-testing (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: latest commit (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "branchName": "feature/renovate-testing",
       "latestCommitDate": "2020-05-12 10:04:06 +0000"
DEBUG: getBranchPr(renovate/node-12.x) (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Got res with 0 results (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: branchExists=true (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Branch has 2 upgrade(s) (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: recreateClosed is false (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: findPr(renovate/node-12.x, build(deps): update node docker tag to v12.16.3, !open) (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: prAlreadyExisted=false (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Checking if PR has been edited (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Checking schedule(at any time, null) (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: No schedule defined (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Branch already exists (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: getBranchPr(renovate/node-12.x) (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Got res with 0 results (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Branch does not need rebasing (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Using parentBranch: renovate/node-12.x (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: manager.getUpdatedPackageFiles() (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Skipping alias FROM (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "currentFrom": "base"
DEBUG: Skipping alias COPY --from (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "currentFrom": "chamber"
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Skipping alias FROM (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "currentFrom": "base"
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Skipping alias FROM (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "currentFrom": "base"
DEBUG: Skipping alias COPY --from (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "currentFrom": "chamber"
DEBUG: Found a multistage build stage name (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Skipping alias FROM (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "currentFrom": "base"
DEBUG: Branch dep is already updated (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: No content changed (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: npm.updateDependency(): devDependencies.@types/node = 12.12.38 (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: No package files need updating (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Getting updated lock files (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: lock file dirs (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "dirs": {
         "yarnLockDirs": [],
         "npmLockDirs": [],
         "pnpmShrinkwrapDirs": [],
         "lernaDirs": []
       }
DEBUG: Writing package.json files (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "packageFiles": ["package.json"]
DEBUG: Writing package-lock.json (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Writing any updated package files (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: No updated lock files in branch (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: No files to commit (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Checking if we can automerge branch (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: mergeStatus=no automerge (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Ensuring PR (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: There are 0 errors and 0 warnings (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: getBranchPr(renovate/node-12.x) (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Got res with 0 results (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Creating PR (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "prTitle": "build(deps): update node docker tag to v12.16.3"
DEBUG: Creating Merge Request: build(deps): update node docker tag to v12.16.3 (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
DEBUG: Pull request creation error (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at get (/usr/local/lib/node_modules/renovate/dist/platform/gitlab/gl-got-wrapper.js:49:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
```

### What would you like to do?

The PR for node is failing to create on Gitlab, while other PRs are created just fine in the same Renovate run. Loglevel Debug only show platform-failure without any other context.

**Comment by tyronedd** [comment]
As shown in the output the branch is created and this is the diff to the target branch:
![image](https://user-images.githubusercontent.com/17970041/81679948-e6491600-9452-11ea-8c13-2e960a60729e.png)

**Comment by rarkins** [comment]
Unfortunately whatever error is being thrown by gitlab is masked by our `platform-failure` error. I've pushed a commit just now that will make sure we always debug log the raw error from GitLab before throwing platform error.

**Comment by tyronedd** [comment]
You're fast! Thought I'd do the same!

It's timing out consistently when trying to create that merge request...

```
 DEBUG: Creating PR (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
        "prTitle": "build(deps): update node docker tag to v12.16.3"
 DEBUG: Creating Merge Request: build(deps): update node docker tag to v12.16.3 (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
 DEBUG: Gitlab API error (repository=_COMPANY_/_PROJECT_/services/client, branch=renovate/node-12.x)
        "err": {
          "name": "TimeoutError",
          "code": "ETIMEDOUT",
          "hostname": "gitlab.com",
          "method": "POST",
          "path": "/api/v4/projects/_COMPANY_%2F_PROJECT_%2Fservices%2Fclient/merge_requests",
          "protocol": "https:",
          "url": "https://gitlab.com/api/v4/projects/_COMPANY_%2F_PROJECT_%2Fservices%2Fclient/merge_requests",
          "gotOptions": {
            "path": "/api/v4/projects/_COMPANY_%2F_PROJECT_%2Fservices%2Fclient/merge_requests",
            "protocol": "https:",
            "hostname": "gitlab.com",
            "hash": "",
            "search": "",
            "pathname": "/api/v4/projects/_COMPANY_%2F_PROJECT_%2Fservices%2Fclient/merge_requests",
            "href": "https://gitlab.com/api/v4/projects/_COMPANY_%2F_PROJECT_%2Fservices%2Fclient/merge_requests",
            "headers": {
              "user-agent": "https://github.com/renovatebot/renovate",
              "accept": "application/json",
              "accept-encoding": "gzip, deflate",
              "content-type": "application/json",
              "Private-token": "**redacted**",
              "content-length": 294216
            },
            "hooks": {
              "beforeError": [],
              "init": [],
              "beforeRequest": [],
              "beforeRedirect": [],
              "beforeRetry": [],
              "afterResponse": []
            },
            "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
            "decompress": true,
            "throwHttpErrors": true,
            "followRedirect": true,
            "stream": false,
            "form": false,
            "json": true,
            "cache": false,
            "useElectronNet": false,
            "hostType": "gitlab",
            "baseUrl": "https://gitlab.com/api/v4/",
            "body": **Cut for brevity**
```
note: ci does not output full content of the body property.

**Comment by tyronedd** [comment]
Ok, so I artificially updated the docker tag from `12.2.0` to `12.16.0` on my testing branch, making the difference only 3 patch versions to `12.16.3` and now the Merge Request created successfully. _Seems_ like the changelog body generated by Renovate was way too large for Gitlab to handle...

**Comment by rarkins** [comment]
Can you reproduce the same on gitlab.com?

**Comment by tyronedd** [comment]
Yeah, I captured the full body output and decoded it:

https://controlc.com/b9dc8624

(Github doesn't let me post log here, says comment is too long)

Tried to create a Merge request with the body content in that snippet and it failed after 1 minute with 500 error:

![image](https://user-images.githubusercontent.com/17970041/81709017-e9073380-9471-11ea-9982-63af246ef4fb.png)

Filesystem says the size of the text is 569,5 kB.

**Comment by tyronedd** [comment]
They did recently switched their CDN to CloudFlare and looking at the response, this could be a CloudFlare timeout and not a timeout of the API behind it.

**Comment by rarkins** [comment]
I think there's a limit to how much text anyone wants to read in a PR anyway :)
