### ISSUE TITLE
Disabling hosting results in Warnings of type Error

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/config-help#754]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```json
{
    "name": "renovate",
    "hostname": "",
    "pid": 25,
    "level": 40,
    "logContext": "",
    "repository": "",
    "registry": "https://our.gitlab.instance:8443",
    "dockerRepository": "group/repo",
    "err": {
        "message": "host-disabled",
        "stack": "Error: host-disabled\n    at Http.request (/usr/src/app/node_modules/renovate/dist/util/http/index.js:92:19)\n    at Http.get (/usr/src/app/node_modules/renovate/dist/util/http/index.js:124:21)\n    at getAuthHeaders (/usr/src/app/node_modules/renovate/dist/datasource/docker/index.js:143:45)\n    at getTags (/usr/src/app/node_modules/renovate/dist/datasource/docker/index.js:333:31)\n    at async Object.getReleases (/usr/src/app/node_modules/renovate/dist/datasource/docker/index.js:485:18)\n    at async getRegistryReleases (/usr/src/app/node_modules/renovate/dist/datasource/index.js:62:17)\n    at async fetchReleases (/usr/src/app/node_modules/renovate/dist/datasource/index.js:172:23)\n    at async Object.getPkgReleases (/usr/src/app/node_modules/renovate/dist/datasource/index.js:230:29)\n    at async Object.lookupUpdates (/usr/src/app/node_modules/renovate/dist/workers/repository/process/lookup/index.js:107:42)\n    at async fetchDepUpdates (/usr/src/app/node_modules/renovate/dist/workers/repository/process/fetch.js:44:32)"
    },
    "msg": "Error obtaining docker token",
    "time": "2020-07-14T12:55:22.711Z",
    "v": 0
}
```

### What would you like to do?

I've added a host rule to disable a host we've decommissioned.  I expected Renovate would ignore this and not attempt renovation of affected dependencies.

It appears however Renovate reports errors that the host is disabled, which we know, since that's what we've configured.

Not entirely sure why these are being raised as warnings given it is explicit configuration but I would like to understand how we can squash the noise in the output from them :)

The host rule is quite basic:

```json
    hostRules: [
        {
            hostName: "our.gitlab.instance",
            enabled: false,
        },
    ],
```

Thanks!

**Comment by rarkins** [comment]
Each datasource needs to add awareness for this new error type and not log it. Not just Docker that would need it.

**Comment by viceice** [comment]
The noise should be reduced when the datasource refactoring is done so we will reduce multiple levels of error handling.

**Comment by rarkins** [comment]
Yeah, but unfortunately we probably need to fix this first as it can cause a non zero exit unnecessarily. I didn't expect others to use the feature so quickly :)

**Comment by adam-moss** [comment]
Oops sorry, I saw it in a commit message and grepped the code, it solves a long-standing issue with us (the host has been decommissioned for quite so time) so jumped the gun somewhat I guess 🤣 

I haven't noticed it hitting an ERROR level to cause a non-zero return, but admittedly I only put the change in earlier today as part of my battle with the ENOMEM error.

**Comment by viceice** [comment]
@rarkins The log above is level=40 which is a warning, so it will only be annoying noise ;-)

**Comment by rarkins** [comment]
Ahh. They're still pretty annoying though.
