### ISSUE TITLE
Github always returning Unauthorized

### ISSUE THREAD

**Issue by candrews** [renovatebot/config-help#756]
### Which Renovate are you using?

Renovate Open Source CLI (Self hosted, docker, `renovate/renovate:latest`)

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant
Here's the log:
```javascript
{
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "config": {},
    "msg": "File config",
    "time": "2020-07-14T20:14:09.156Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "config": {
        "dryRun": true,
        "logFile": "/tmp/log"
    },
    "msg": "CLI config",
    "time": "2020-07-14T20:14:09.157Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "config": {
        "hostRules": [{
            "hostType": "github",
            "domainName": "github.com",
            "token": "***********"
        }],
        "token": "***********"
    },
    "msg": "Env config",
    "time": "2020-07-14T20:14:09.157Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "config": {
        "hostRules": [{
            "hostType": "github",
            "domainName": "github.com",
            "token": "***********"
        }],
        "token": "***********",
        "dryRun": true,
        "logFile": "/tmp/log"
    },
    "msg": "Combined config",
    "time": "2020-07-14T20:14:09.157Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "msg": "Using default github endpoint: https://api.github.com/",
    "time": "2020-07-14T20:14:09.158Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "token": "***********",
    "err": {
        "name": "HTTPError",
        "hostname": "api.github.com",
        "method": "GET",
        "path": "/user",
        "protocol": "https:",
        "url": "https://api.github.com/user",
        "gotOptions": {
            "path": "/user",
            "protocol": "https:",
            "hostname": "api.github.com",
            "hash": "",
            "search": "",
            "pathname": "/user",
            "href": "https://api.github.com/user",
            "retry": {
                "methods": {},
                "statusCodes": {},
                "errorCodes": {}
            },
            "headers": {
                "user-agent": "https://github.com/renovatebot/renovate",
                "accept": "application/vnd.github.v3+json",
                "authorization": "***********",
                "accept-encoding": "gzip, deflate"
            },
            "hooks": {
                "beforeRequest": [],
                "beforeRedirect": [null],
                "beforeRetry": [],
                "afterResponse": [],
                "beforeError": [],
                "init": []
            },
            "decompress": true,
            "throwHttpErrors": true,
            "followRedirect": true,
            "stream": false,
            "form": false,
            "json": true,
            "cache": false,
            "useElectronNet": false,
            "method": "GET",
            "hostType": "github",
            "baseUrl": "https://api.github.com/"
        },
        "statusCode": 401,
        "statusMessage": "Unauthorized",
        "headers": {
            "server": "GitHub.com",
            "date": "Tue, 14 Jul 2020 20:14:09 GMT",
            "content-type": "application/json; charset=utf-8",
            "content-length": "83",
            "connection": "close",
            "status": "401 Unauthorized",
            "x-github-media-type": "github.v3; format=json",
            "x-ratelimit-limit": "60",
            "x-ratelimit-remaining": "53",
            "x-ratelimit-reset": "1594758606",
            "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
            "access-control-allow-origin": "*",
            "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
            "x-frame-options": "deny",
            "x-content-type-options": "nosniff",
            "x-xss-protection": "1; mode=block",
            "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
            "content-security-policy": "default-src 'none'",
            "vary": "Accept-Encoding, Accept, X-Requested-With",
            "x-github-request-id": "DECA:3533:528ED7:C4FAD4:5F0E1211"
        },
        "body": {
            "message": "Bad credentials",
            "documentation_url": "https://developer.github.com/v3"
        },
        "message": "Response code 401 (Unauthorized)",
        "stack": "HTTPError: Response code 401 (Unauthorized)\n    at EventEmitter.<anonymous> (/usr/src/app/node_modules/got/source/as-promise.js:74:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    },
    "msg": "GitHub failure: Bad credentials",
    "time": "2020-07-14T20:14:09.291Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "err": {
        "hostType": "github",
        "err": {
            "name": "HTTPError",
            "hostname": "api.github.com",
            "method": "GET",
            "path": "/user",
            "protocol": "https:",
            "url": "https://api.github.com/user",
            "gotOptions": {
                "path": "/user",
                "protocol": "https:",
                "hostname": "api.github.com",
                "hash": "",
                "search": "",
                "pathname": "/user",
                "href": "https://api.github.com/user",
                "retry": {
                    "methods": {},
                    "statusCodes": {},
                    "errorCodes": {}
                },
                "headers": {
                    "user-agent": "https://github.com/renovatebot/renovate",
                    "accept": "application/vnd.github.v3+json",
                    "authorization": "***********",
                    "accept-encoding": "gzip, deflate"
                },
                "hooks": {
                    "beforeRequest": [],
                    "beforeRedirect": [null],
                    "beforeRetry": [],
                    "afterResponse": [],
                    "beforeError": [],
                    "init": []
                },
                "decompress": true,
                "throwHttpErrors": true,
                "followRedirect": true,
                "stream": false,
                "form": false,
                "json": true,
                "cache": false,
                "useElectronNet": false,
                "method": "GET",
                "hostType": "github",
                "baseUrl": "https://api.github.com/"
            },
            "statusCode": 401,
            "statusMessage": "Unauthorized",
            "headers": {
                "server": "GitHub.com",
                "date": "Tue, 14 Jul 2020 20:14:09 GMT",
                "content-type": "application/json; charset=utf-8",
                "content-length": "83",
                "connection": "close",
                "status": "401 Unauthorized",
                "x-github-media-type": "github.v3; format=json",
                "x-ratelimit-limit": "60",
                "x-ratelimit-remaining": "53",
                "x-ratelimit-reset": "1594758606",
                "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
                "access-control-allow-origin": "*",
                "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
                "x-frame-options": "deny",
                "x-content-type-options": "nosniff",
                "x-xss-protection": "1; mode=block",
                "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
                "content-security-policy": "default-src 'none'",
                "vary": "Accept-Encoding, Accept, X-Requested-With",
                "x-github-request-id": "DECA:3533:528ED7:C4FAD4:5F0E1211"
            },
            "body": {
                "message": "Bad credentials",
                "documentation_url": "https://developer.github.com/v3"
            }
        },
        "message": "external-host-error",
        "stack": "Error: external-host-error\n    at handleGotError (/usr/src/app/node_modules/renovate/dist/util/http/github.js:67:19)\n    at GithubHttp.request (/usr/src/app/node_modules/renovate/dist/util/http/github.js:155:13)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    },
    "msg": "Error authenticating with GitHub",
    "time": "2020-07-14T20:14:09.293Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 60,
    "logContext": "TAXNK1fYr",
    "msg": "Authentication failure",
    "time": "2020-07-14T20:14:09.294Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "msg": "Renovate exiting",
    "time": "2020-07-14T20:14:09.295Z",
    "v": 0
} {
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 30,
    "logContext": "TAXNK1fYr",
    "loggerErrors": [{
        "name": "renovate",
        "level": 60,
        "logContext": "TAXNK1fYr",
        "msg": "Authentication failure"
    }],
    "msg": "Renovate is exiting with a non-zero code due to the following logged errors",
    "time": "2020-07-14T20:14:09.295Z",
    "v": 0
}
```

### What would you like to do?
I'm trying to run renovate against my Gitlab instance.

I've created a Github Token using my Github account, and I've provided that token in the `GITHUB_COM_TOKEN` environment variable when I run docker like this:
`docker run -e GITHUB_COM_TOKEN="4...e" -e NEXUS_USERNAME="service-renovate" -e NEXUS_PASSWORD="redacted" -e NEXUS_URL="https://repo.redacted" -e RENOVATE_TOKEN="D...z"  --rm -v "$(pwd)/config.js:/usr/src/app/config.js:Z"`

Renovate fails with this output:
```
FATAL: Authentication failure
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "TAXNK1fYr",
           "msg": "Authentication failure"
         }
       ]
```

I know the token is valid - I've tested it using curl like this:
`curl -H "Authorization: token 4...e" https://api.github.com`

Here's my configuration:
```javascript
const nexusUsername = process.env.NEXUS_USERNAME;
const nexusPassword = process.env.NEXUS_PASSWORD;
const nexusUrl = process.env.NEXUS_URL;
const gitPrivateKey = process.env.GIT_PRIVATE_KEY ? process.env.GIT_PRIVATE_KEY.replace(/\\n/g, '\n') : undefined;
const npmAuth = btoa(nexusUsername + ":" + nexusPassword);

if(! nexusUsername){
    console.log("The NEXUS_USERNAME environment variable must be set")
    process.exit(1);
}
if(! nexusPassword){
    console.log("The NEXUS_PASSWORD environment variable must be set")
    process.exit(1);
}

module.exports = {
    platform: 'gitlab',
    endpoint: 'https://git.redacted/api/v4/',
    packageRules: [{
        managers: ["gradle"],
        registryUrls: ["https://plugins.gradle.org/m2/"]
    }, {
        managers: ["maven", "gradle"],
        registryUrls: [nexusUrl + "/repository/maven-public/", nexusUrl + "/repository/redacted-releases/"]
    },
    {
        managers: ["npm"],
        registryUrls: [nexusUrl + "/repository/npm-public/"]
    }],
    hostRules: [{
        hostName: "repo.redacted",
        username: nexusUsername,
        password: nexusPassword
    },
    {
        hostName: "registry.redacted",
        username: nexusUsername,
        password: nexusPassword
    }],
    gitAuthor: "Renovate Service <service-renovate@redacted>",
    gitPrivateKey: gitPrivateKey,
    labels: ["renovate"],
    ignoreNpmrcFile: true,
    npmrc: "registry=" + nexusUrl + "/repository/npm-public/\nalways-auth=truei\n_auth=\"\"",
    logLevel: 'debug',
    onboardingConfig: { extends: ["config:base"] },
    autodiscover: true
};

```

I cannot figure out how to get Renovate to work with a Github token... can you help please?

**Comment by rarkins** [comment]
The log shows that your file config is not being read. Ie nothing in config.js is recognised

**Comment by candrews** [comment]
The problem ended up being that there is no `btoa` function defined in node... I had to use `Buffer.from(something).toString('base64')` instead.

Can renovate display a better error when this happens? This log output:
```javascript
{
    "name": "renovate",
    "hostname": "1aa5ca955860",
    "pid": 36,
    "level": 20,
    "logContext": "TAXNK1fYr",
    "config": {},
    "msg": "File config",
    "time": "2020-07-14T20:14:09.156Z",
    "v": 0
}
```
Is not clearly indicating a config.js parsing error... and it would be really nice if it could. Even better, this stdout/stderror output:
```
FATAL: Authentication failure
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "TAXNK1fYr",
           "msg": "Authentication failure"
         }
       ]
```
should really say that config.js is invalid/unparseable, not that there's an authentication failure.

**Comment by rarkins** [comment]
A PR for this would be welcome

**Comment by candrews** [comment]
Also - thank you very much for help. I realized I forgot to say that before, and I'm sorry for that.

Seriously, thank you.
