### ISSUE TITLE
Unexpected token in config.js

### ISSUE THREAD

**Issue by tigattack** [renovatebot/config-help#761]
### Which Renovate are you using?

WhiteSource Renovate
### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant
```text
FATAL: Could not parse config file
        /usr/src/app/config.js:2
           "onboardingConfig": { "extends": ["config:base"] }
                             ^

       SyntaxError: Unexpected token ':'
           at wrapSafe (internal/modules/cjs/loader.js:1054:16)
           at Module._compile (internal/modules/cjs/loader.js:1102:27)
           at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
           at Module.load (internal/modules/cjs/loader.js:986:32)
           at Function.Module._load (internal/modules/cjs/loader.js:879:14)
           at Module.require (internal/modules/cjs/loader.js:1026:19)
           at require (internal/modules/cjs/helpers.js:72:18)
           at Object.getConfig (/usr/src/app/node_modules/renovate/dist/config/file.js:19:18)
           at Object.parseConfigs (/usr/src/app/node_modules/renovate/dist/config/index.js:61:72)
           at processTicksAndRejections (internal/process/task_queues.js:97:5)
           at async /usr/src/app/src/server.js:1:4562
```

### What would you like to do?
I have the following in docker-compose.yaml:
```yaml
    volumes:
      - "./config.js:/usr/src/app/config.js:rw" # Renovate OSS configuration
```
When I run `docker-compose up -d` and `docker logs <container>` I see the error from above in the logs. Everything else appears to be fine.

I'm running the `whitesource/renovate:1.0.1` image.

`config.js` is just this:
```text
{
    "onboardingConfig": { "extends": ["config:base"] }
}
```

**Comment by rarkins** [comment]
That's not a valid JS file. Call it config.json instead if it's a valid JSON file

**Comment by tigattack** [comment]
Thanks. I assume Renovate will accept config.json just as it would config.js?  
It was configured by someone else, but I was confused why it was a JS file, however I took it in stride since it worked fine in 0.18.5! 🙂

**Comment by rarkins** [comment]
It reads either config.js or config.json. I doubt it ever worked if you put json content in a .js file
