### ISSUE TITLE
yarn lock file error for private azure registry

### ISSUE THREAD

**Issue by rkrabek** [renovatebot/config-help#829]
### Which Renovate are you using?
Other (please write below)
Visual Studio Marketplace Extension

### Which platform are you using?
Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant
Logs relevant to the error:
```
DEBUG: Getting updated lock files (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: lock file dirs (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "dirs": {
         "yarnLockDirs": ["my-app/yarn.lock"],
         "npmLockDirs": [],
         "pnpmShrinkwrapDirs": [],
         "lernaDirs": []
       }
DEBUG: Writing repo .npmrc (/tmp/renovate/repos/azure/MyProject/testRepo) (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Writing package.json files (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "packageFiles": ["my-app/package.json"]
DEBUG: Writing any updated package files (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Writing my-app/package.json (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: npmrc file found in repository (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Generating yarn.lock for my-app (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Spawning yarn install to create /tmp/renovate/repos/azure/MyProject/testRepo/my-app/yarn.lock (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Updating yarn.lock only - skipping node_modules (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Using node constraint "^10.16.0" from package.json (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Performing yarn dedupe fewer (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Executing command (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "command": "yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts"
DEBUG: lock file error (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts",
         "stdout": "yarn install v1.22.4\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo If you think this is a bug, please open a bug report with the information provided in \"/tmp/renovate/repos/azure/MyProject/testRepo/my-app/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
         "stderr": "error An unexpected error occurred: \"https://**redacted**@types/node/-/node-14.0.1.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "message": "Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror An unexpected error occurred: \"https://**redacted**@types/node/-/node-14.0.1.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "stack": "Error: Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror An unexpected error occurred: \"https://**redacted**@types/node/-/node-14.0.1.tgz: Request failed \\\"401 Unauthorized\\\"\".\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       },
       "type": "yarn"
DEBUG: No updated lock files in branch (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
```

### What would you like to do?

Have Renovate be able to update the lock files in the PRs it makes. Currently in the PRs there is a comment  about an Artifact update problem with the following error: error 

```
An unexpected error occurred: "https://myproject.pkgs.visualstudio.com/_packaging/PrivateAzurePackageFeedName/npm/registry/@types/node/-/node-14.0.1.tgz: Request failed \"401 Unauthorized\"".
```

The packages are referenced via a private registry which I believe I have configured correctly since renovate doesn't seem to have an issue in the dependency lookup phase, but just the yarn install step. I've also set ignoreNpmrcFile to true because I'm passing the npmrc config in via the renovate build task so it can inject the unencrypted PAT at runtime.

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base", "group:jsTest", "group:linters"],
  "enabledManagers": ["npm"],
  "ignoreNpmrcFile": true,
  "includePaths": ["**/my-app/**"],
  "rangeStrategy": "bump"
}
```

Is there something in the configs that would cause the dependency lookups to succeed but the yarn install step to fail?

Thanks in advance!

**Comment by rarkins** [comment]
If yarn install is failing then it's because yarn can't access a `.npmrc` file with the required credentials.

**Comment by rkrabek** [comment]
In the Renovate VSTS extension: https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me&targetId=19422243-19b9-4d85-9ca6-bc961861d287
There is an "additional args" field in the task which I've passed in --npmrc as a field and the Azure Devops build tasks allow you to inject variables at runtime which is what I've done with the password in the form of $(RenovateFeedToken)

![image](https://user-images.githubusercontent.com/9980031/91200018-76823280-e6b3-11ea-968e-5acaeb173c6b.png)

**Comment by rarkins** [comment]
If you also have an npmrc file in the repo, can you try deleting it?

**Comment by rkrabek** [comment]
Looks like it's the same error, just hits on a different package sometimes just depending on what PRs are open/which ones I've tagged with "rebase!" for them to update. I tried removing both our .npmrc and our docker.npmrc files

```
DEBUG: lock file error (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts",
         "stdout": "yarn install v1.22.4\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo If you think this is a bug, please open a bug report with the information provided in \"/tmp/renovate/repos/azure/MyProject/testRepo/my-app/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
         "stderr": "error An unexpected error occurred: \"https://**redacted**@types/range-parser/-/range-parser-1.2.3.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "message": "Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror An unexpected error occurred: \"https://**redacted**@types/range-parser/-/range-parser-1.2.3.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "stack": "Error: Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror An unexpected error occurred: \"https://**redacted**@types/range-parser/-/range-parser-1.2.3.tgz: Request failed \\\"401 Unauthorized\\\"\".\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       },
       "type": "yarn"
DEBUG: No updated lock files in branch (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
```

**Comment by rkrabek** [comment]
I'm assuming the debug log of "npmrc file found in repository" is referencing the npmrc string that I passed in via the build task arguments

**Comment by rarkins** [comment]
> I'm assuming the debug log of "npmrc file found in repository" is referencing the npmrc string that I passed in via the build task arguments

It's intended to be a check if there's a file in the repo. But it's possible it was written there during a previous branch? How many times was the yarn.lock generated that run?

**Comment by rkrabek** [comment]
That run there was 1 instance of Generating yarn.lock

Good point on the previous branches being updated, they hadn't rebased so still had npmrc files in them. I went ahead and abandoned all the open PRs, deleted the branches, and ran the pipeline again basically from a clean slate. I verified there was no npmrc file in the created branches and in this run there were 2 instances of yarn.lock generation, seemingly with the same error and it still appears to find an npmrc file

This is the output for one of the instances, the other one is pretty much the same, just a different package and branch:
```
DEBUG: npmrc file found in repository (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Generating yarn.lock for my-app (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Spawning yarn install to create /tmp/renovate/repos/azure/MyProject/testRepo/my-app/yarn.lock (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Updating yarn.lock only - skipping node_modules (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Using node constraint "^10.16.0" from package.json (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Performing yarn dedupe fewer (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Executing command (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "command": "yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts"
DEBUG: lock file error (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts",
         "stdout": "yarn install v1.22.4\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo If you think this is a bug, please open a bug report with the information provided in \"/tmp/renovate/repos/azure/MyProject/testRepo/my-app/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
         "stderr": "error An unexpected error occurred: \"https://**redacted**@types/range-parser/-/range-parser-1.2.3.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "message": "Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror An unexpected error occurred: \"https://**redacted**@types/range-parser/-/range-parser-1.2.3.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "stack": "Error: Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror An unexpected error occurred: \"https://**redacted**@types/range-parser/-/range-parser-1.2.3.tgz: Request failed \\\"401 Unauthorized\\\"\".\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       },
       "type": "yarn"
DEBUG: No updated lock files in branch (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Branch timestamp: 2020-05-14T16:21:36Z (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: PR is older than a day, raise PR with lock file errors (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: 1 file(s) to commit (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Committing files to branch renovate/apollo-graphql-packages (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
 INFO: Branch created (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "commitHash": "d5fd1ed"
DEBUG: Ensuring PR (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: There are 0 errors and 0 warnings (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: getBranchPr(renovate/apollo-graphql-packages) (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: getPrList() (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Forcing PR because of artifact errors (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: Creating PR (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "prTitle": "Update Apollo GraphQL packages"
 INFO: PR created (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "pr": 1794045,
       "prTitle": "Update Apollo GraphQL packages"
DEBUG: Created Pull Request #1794045 (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
 WARN: artifactErrors (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "artifactErrors": [
         {
           "lockFile": "my-app/yarn.lock",
           "stderr": "error An unexpected error occurred: \"https://msasg.pkgs.visualstudio.com/_packaging/ProductInsights/npm/registry/@types/range-parser/-/range-parser-1.2.3.tgz: Request failed \\\"401 Unauthorized\\\"\".\n"
         }
       ]
DEBUG: ensureComment(1794045, ⚠️ Artifact update problem, content) (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
 INFO: Comment added (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
       "issueNo": 1794045,
       "topic": "⚠️ Artifact update problem"
DEBUG: Updating status check state to failed (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
DEBUG: setBranchStatus(renovate/apollo-graphql-packages, renovate/artifacts, Artifact file update failure, red, undefined) - Not supported by Azure DevOps (yet!) (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
```

**Comment by rarkins** [comment]
It's still finding a `.npmrc` file in the file system: `DEBUG: npmrc file found in repository`. If that's the first branch in the log and it prints it then it means there's still a file there somehow.

**Comment by rkrabek** [comment]
Ok I've checked out the PR branch as well as master, done a global search in VSCode for files with the name or containing npmrc and have come up empty handed. I'm reasonably certain I do not have an npmrc file in my repo except for in the git commit history.

Is there any other way renovate is identifying npmrc files other than finding a file by its name in the repository?

Is there a way to prevent renovate from recognizing the npmrc file? I already have `"ignoreNpmrcFile": true` in the configuration in case passing in the npmrc string config didn't already make it ignore any files it found.

Are you sure renovate doesn't take the npmrc string from the config and create a file with it? It would seem the debug output a few lines above found npmrc file indicates it's writing an npmrc file into the repo:
```
DEBUG: Writing repo .npmrc (/tmp/renovate/repos/azure/MyProject/testRepo) (repository=MyProject/testRepo, branch=renovate/apollo-graphql-packages)
```

**Comment by viceice** [comment]
yes renovate is writing you config npmrc to repo root. also you should quote the `--npmrc` argument value in your renovate config as that are commandline arguments

**Comment by viceice** [comment]
maybe related to jycouet/VSTSExtensions#32

**Comment by rkrabek** [comment]
Thanks for the clarification, good to know on the quotes, unfortunately that doesn't change the behavior of the run itself.

The good news is I have a solution for that issue! I'll go give the issue a reply when I have some time later on but it should be reasonably simple.

Bad news is I've only managed to get private package feeds to work a brand new project, and not my existing project even though the way I set up the authentication is the same.

I wonder if it has something to do with the url of the repo/package feed, in older projects the url is https://orgName.visualstudio.com/projectName/_git/repoName whereas the new ones after rebranding from VSTS to azure devops are https://dev.azure.com/orgName/projectName/_git/repoName but I assumed it was compatible from other issues like #203 where they appear to be referencing visualstudio url package feeds

**Comment by rkrabek** [comment]
Is there a way to specify where renovate writes the npmrc file to? My package.json is 1 level deeper than the root of the repo. I'm guessing the npmrc file not being adjacent to the package.json may be causing my issues

file structure:
repoRootFolder/
 -renovate.json
 -my-app-folder/
 --package.json

**Comment by viceice** [comment]
I need to check the code, but my guess is renovate writes the `.npmrc` next to the current package.json it is working on.

You can always try to run renovate from your local pc with `npx renovate <args>` or `docker run --rm -it renovate/renovate:slim <args>` to test, so we can be sure it's a renovate or renovateme issue.

**Comment by rkrabek** [comment]
No luck running it locally either, I got a dependency lookup error, maybe you were right on the issue with having a problem pulling form private org-scoped azure registries. I did come across this in the repository which worked when everything else had failed: https://github.com/renovatebot/renovate/blob/master/docs/usage/setup-azure-devops.md
