### ISSUE TITLE
File creation and repo checkout failed due to long filename

### ISSUE THREAD

**Issue by rkrabek** [renovatebot/config-help#835]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Repository started (repository=MyProject/testRepo)
       "renovateVersion": "22.17.0"
 WARN: Host error (repository=MyProject/testRepo)
       "hostType": "git",
       "lookupName": undefined,
       "err": {
         "task": {
           "concatStdErr": false,
           "format": "utf-8",
           "commands": [
             "clone",
             "--depth=2",
             "--config=http.extraheader=AUTHORIZATION: basic ***PAT***",
             "https://myOrg.visualstudio.com/MyProject/_git/testRepo",
             "."
           ]
         },
         "message": "Cloning into '.'...\nerror: unable to create file [removed198charFilePath]: Filename too long\nUpdating files:  51% (1693/3284)\rUpdating files:  52% (1708/3284)\rUpdating files:  53% (1741/3284)\rUpdating files:  54% (1774/3284)\rUpdating files:  55% (1807/3284)\rUpdating files:  56% (1840/3284)\rUpdating files:  57% (1872/3284)\rUpdating files:  58% (1905/3284)\rUpdating files:  59% (1938/3284)\rUpdating files:  60% (1971/3284)\rUpdating files:  61% (2004/3284)\rUpdating files:  62% (2037/3284)\rUpdating files:  63% (2069/3284)\rUpdating files:  64% (2102/3284)\rUpdating files:  65% (2135/3284)\rUpdating files:  66% (2168/3284)\rUpdating files:  67% (2201/3284)\rUpdating files:  68% (2234/3284)\rUpdating files:  69% (2266/3284)\rUpdating files:  70% (2299/3284)\rUpdating files:  71% (2332/3284)\rUpdating files:  72% (2365/3284)\rUpdating files:  73% (2398/3284)\rUpdating files:  74% (2431/3284)\rUpdating files:  75% (2463/3284)\rUpdating files:  76% (2496/3284)\rUpdating files:  77% (2529/3284)\rUpdating files:  78% (2562/3284)\rUpdating files:  79% (2595/3284)\rUpdating files:  80% (2628/3284)\rUpdating files:  81% (2661/3284)\rUpdating files:  82% (2693/3284)\rUpdating files:  83% (2726/3284)\rUpdating files:  84% (2759/3284)\rUpdating files:  85% (2792/3284)\rUpdating files:  86% (2825/3284)\rUpdating files:  87% (2858/3284)\rUpdating files:  88% (2890/3284)\rUpdating files:  89% (2923/3284)\rUpdating files:  90% (2956/3284)\rUpdating files:  91% (2989/3284)\rUpdating files:  92% (3022/3284)\rUpdating files:  93% (3055/3284)\rUpdating files:  94% (3087/3284)\rUpdating files:  95% (3120/3284)\rUpdating files:  96% (3153/3284)\rUpdating files:  97% (3186/3284)\rUpdating files:  98% (3219/3284)\rUpdating files:  99% (3252/3284)\rUpdating files: 100% (3284/3284)\rUpdating files: 100% (3284/3284), done.\nfatal: unable to checkout working tree\nwarning: Clone succeeded, but checkout failed.\nYou can inspect what was checked out with 'git status'\nand retry with 'git restore --source=HEAD :/'\n\n",
         "stack": "Error: Cloning into '.'...\nerror: unable to create file [sameRemoved198charFilePath]: Filename too long\nUpdating files:  51% (1693/3284)\rUpdating files:  52% (1708/3284)\rUpdating files:  53% (1741/3284)\rUpdating files:  54% (1774/3284)\rUpdating files:  55% (1807/3284)\rUpdating files:  56% (1840/3284)\rUpdating files:  57% (1872/3284)\rUpdating files:  58% (1905/3284)\rUpdating files:  59% (1938/3284)\rUpdating files:  60% (1971/3284)\rUpdating files:  61% (2004/3284)\rUpdating files:  62% (2037/3284)\rUpdating files:  63% (2069/3284)\rUpdating files:  64% (2102/3284)\rUpdating files:  65% (2135/3284)\rUpdating files:  66% (2168/3284)\rUpdating files:  67% (2201/3284)\rUpdating files:  68% (2234/3284)\rUpdating files:  69% (2266/3284)\rUpdating files:  70% (2299/3284)\rUpdating files:  71% (2332/3284)\rUpdating files:  72% (2365/3284)\rUpdating files:  73% (2398/3284)\rUpdating files:  74% (2431/3284)\rUpdating files:  75% (2463/3284)\rUpdating files:  76% (2496/3284)\rUpdating files:  77% (2529/3284)\rUpdating files:  78% (2562/3284)\rUpdating files:  79% (2595/3284)\rUpdating files:  80% (2628/3284)\rUpdating files:  81% (2661/3284)\rUpdating files:  82% (2693/3284)\rUpdating files:  83% (2726/3284)\rUpdating files:  84% (2759/3284)\rUpdating files:  85% (2792/3284)\rUpdating files:  86% (2825/3284)\rUpdating files:  87% (2858/3284)\rUpdating files:  88% (2890/3284)\rUpdating files:  89% (2923/3284)\rUpdating files:  90% (2956/3284)\rUpdating files:  91% (2989/3284)\rUpdating files:  92% (3022/3284)\rUpdating files:  93% (3055/3284)\rUpdating files:  94% (3087/3284)\rUpdating files:  95% (3120/3284)\rUpdating files:  96% (3153/3284)\rUpdating files:  97% (3186/3284)\rUpdating files:  98% (3219/3284)\rUpdating files:  99% (3252/3284)\rUpdating files: 100% (3284/3284)\rUpdating files: 100% (3284/3284), done.\nfatal: unable to checkout working tree\nwarning: Clone succeeded, but checkout failed.\nYou can inspect what was checked out with 'git status'\nand retry with 'git restore --source=HEAD :/'\n\n\n    at GitExecutorChain.onFatalException (C:\\Users\\rokrabek\\AppData\\Roaming\\nvm\\v10.16.0\\node_modules\\renovate\\node_modules\\simple-git\\src\\lib\\runners\\git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (C:\\Users\\rokrabek\\AppData\\Roaming\\nvm\\v10.16.0\\node_modules\\renovate\\node_modules\\simple-git\\src\\lib\\runners\\git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\rokrabek\\AppData\\Roaming\\nvm\\v10.16.0\\node_modules\\renovate\\node_modules\\simple-git\\src\\lib\\runners\\git-executor-chain.js:6:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: External host error causing abort - skipping (repository=MyProject/testRepo)
 INFO: Repository finished (repository=MyProject/testRepo)
       "durationMs": 17172
```

### What would you like to do?

Trying to get renovate CLI to run with my azure project to debug npmrc issues with the VSTS extension. I'm able to get this config to run with a new test project but it fails on my existing project. The errors say it's because our file structure is too deep but I'm wondering if there's something else going on/I messed up the configs as I'm able to get farther than this using the extension.

Side note: I'm also getting a warning `WARN: Config needs migrating`  is that something I should be paying attention to?

Current config:
```
module.exports = {
  platform: 'azure',
  endpoint: 'https://myOrg.visualstudio.com/',
  dryRun: true,
  repositories: ['MyProject/testRepo'],
  token: '******',
  hostRules: [
    {
      hostType: 'npm',
      endpoint: 'https://myOrg.pkgs.visualstudio.com/_packaging/MyProjectFeed/npm/registry/',
      username: 'myOrg',
      password: '******'
    }
  ],
  onboarding: false,
  requireConfig: false,
  trustLevel: 'high'
};
```

**Comment by rarkins** [comment]
You don't need to worry about the Config needs migrating message. The migrated config is already in use.

You should google search for git and "Filename too long" to find the appropriate solution for your OS. If you find it's something Renovate *could* do then feel free to create a feature request for it.

On a separate not, did Renovate log your PAT in the "Host error"? (I assume you replaced it with `***PAT***` yourself?). We normally try to redact all logs so you don't need to do that, so I'd like to take a look at that. How/where do you configure the PAT?

**Comment by rkrabek** [comment]
Got it that fixed the error thanks!

Yes to both, it was not redacted and it's a string in the config exactly as you see it with the *'s replaced by the token
