### ISSUE TITLE
Managing multiple NPM private registries

### ISSUE THREAD

**Issue by nimmoadam** [renovatebot/config-help#836]
### Which Renovate are you using?

Renovate Open Source CLI

Other (please write below)

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

I have multiple private npm registries with different NPM_TOKEN for each registry. How should I configure that? 

I see the following error, after on-boarding one of the repos, which has different private npm registry.

```
DEBUG: Found package lookup warnings in onboarding (repository=<REPO_NAME>)
[2020-08-30T20:38:18.124Z]        "warnings": [
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/console-i18n",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/<package1>",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/console-platform-express-setup",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/console-platform-log4js-utils",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/console-platform-nconf",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/console-platform-template-render",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/pal",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/e2e-common",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/eslint-plugin-analytics-best-practices",
[2020-08-30T20:38:18.124Z]          "Failed to look up dependency @console/<package2>"
[2020-08-30T20:38:18.124Z]        ],
```

Along with this, I also see the following error.

```
[2020-08-31T02:42:22.786Z] ERROR: Repository has unknown error (repository=<REPO_NAME>)
[2020-08-31T02:42:22.786Z]        "err": {
[2020-08-31T02:42:22.786Z]          "task": {
[2020-08-31T02:42:22.786Z]            "concatStdErr": false,
[2020-08-31T02:42:22.786Z]            "format": "utf-8",
[2020-08-31T02:42:22.786Z]            "commands": [
[2020-08-31T02:42:22.786Z]              "log",
[2020-08-31T02:42:22.786Z]              "-1",
[2020-08-31T02:42:22.786Z]              "--pretty=format:%ae",
[2020-08-31T02:42:22.786Z]              "origin/renovate/configure"
[2020-08-31T02:42:22.786Z]            ]
[2020-08-31T02:42:22.786Z]          },
[2020-08-31T02:42:22.786Z]          "message": "fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
[2020-08-31T02:42:22.787Z]          "stack": "Error: fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at GitExecutorChain.onFatalException (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_12.16.3/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_12.16.3/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_12.16.3/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
[2020-08-31T02:42:22.787Z]        }
```

I'm not sure if the second error snippet is because we are unable to authenticate with a private npm registry.

**My Configuration**

- In my renovate-bot repository
**config.js**

```
module.exports = {
  endpoint: '<GITHUB_ENDPOINT>',
  npmrc: `registry=https://<DOMAIN_1>/<NP_PATH>\nalways-auth=true\n_auth=${process.env.NPM_TOKEN}`,
  repositories: [
    '<REPO_NAME_1>',
    '<REPO_NAME>'
  ],
};
```

Using a script to trigger the renovate cli.
`renovate --log-level debug --host-rules "[{\"hostType\": \"maven\",\"endpoint\": \"https:\/\/<DOMAIN>:443\/artifactory\",\"username\": \"${ID}\",\"password\": \"${PASSWORD}\"}, {\"hostType\": \"docker\",\"hostName\": \"<DOMAIN>\",\"username\": \"${ID}\",\"password\": \"${PASSWORD}\"}]"`

I don't have.npmrc in renovate-bot's repository. 

in <REPO_NAME>, my npmrc is  -- Problem is only with this repo.

```
@console:registry=https://<DOMAIN_NPM_1>/
registry=https://registry.npmjs.org/
```
the authentication is done from travis.yml as:

```
before_install:
echo "@console:registry=http://<DOMAIN_NPM_1>/" >> ~/.npmrc
echo "//<DOMAIN_NPM_1>/:_authToken=\${NPM_TOKEN}" >> ~/.npmrc
```

in <REPO_NAME_1>, my npmrc is ------ this is already being authenticated and working as expected.

```
_auth = ${NPM_AUTH}
registry=https://<DOMAIN_NPM_2>/artifactory/api/npm/entity-bm-npm-virtual/
always-auth=true
```

**Comment by rarkins** [comment]
Try not to mix `.npmrc` files in the repo with Renovate's config. You can configure repository-specific repos this way:

```js
module.exports = {
  endpoint: '<GITHUB_ENDPOINT>',
  npmrc: `registry=https://<DOMAIN_1>/<NP_PATH>\nalways-auth=true\n_auth=${process.env.NPM_TOKEN}`,
  repositories: [
    { repository: '<REPO_NAME_1>', npmrc: '<some different npmrc>' },
    '<REPO_NAME>'
  ],
};
```
