### ISSUE TITLE
assigneesFromCodeOwners set to true but GitLab MR are not assigned to code owners

### ISSUE THREAD

**Issue by cykl** [renovatebot/config-help#906]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted (CE)

### Have you checked the logs? Don't forget to include them if relevant

Yes.

### What would you like to do?

I had like all merge requests to be automatically assigned to code owners as defined in `.gitlab/CODEOWNERS` files (if it exists). 

Config.json file looks like:

```json
{
  "assigneesFromCodeOwners": true,
[...]
}
```

And my test repository contains a valid CODEOWNERS file:

```
$ cat .gitlab/CODEOWNERS 
* @cmathieu
```

However, PR are still unassigned. I search for something like CODEOWNERS or owners in debug mode but failed to find something relevant. Is my configuration wrong? Any troubleshooting hint? 

Extra question: If there is no CODEOWNERS file, is it possible to assign repository owners or maintainers? (our strategy is to use a central configuration as much as possible and to not require repositories to add a renovate configuration file)

**Comment by cykl** [comment]
Logs contains those two lines:

```
 INFO: PR created (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
       "pr": 14,
       "prTitle": "Update dependency xxx:xxx to v0.0.33"
DEBUG: Created Merge Request #14 (repository=backend/pilot-java-api, branch=renovate/xxxx)
```

If I understand source code correctly, assignees are set just before this last debug statement

```
   // Skip assign and review if automerging PR
    if (
      config.automerge &&
      !config.assignAutomerge &&
      (await getBranchStatus()) !== BranchStatus.red
    ) {
      logger.debug(
        `Skipping assignees and reviewers as automerge=${config.automerge}`
      );
    } else {
      await addAssigneesReviewers(config, pr);
    }
    logger.debug(`Created ${pr.displayNumber}`);
```

As _Skipping assignees and reviewers as automerge..._ is not printed I expect that addAssigneesReviewers is invoked. As no error is printed it likely means that `codeOwnersForPr`  returns an empty list. 

As my `.gitlab/CODEOWNERS` file contains exactly `* @cmathieu` (md5sum 4c64acb35a214ef4287bab8bf21a3639) I don't know what could be wrong. Could it be related to my config or should I open an issue?

**Comment by rarkins** [comment]
@cykl I added some debugging logs to the CODEOWNERS logic yesterday in this file: https://github.com/renovatebot/renovate/blob/0f9a61e4cac057d00eb71a853328a1b1fc7092bd/lib/workers/pr/code-owners.ts

The next time a MR is created you should see something that may help. I verified the contents of your CODEOWNERS with our existing logic and it returns your username as expected.

**Comment by cykl** [comment]
Thank you for that.

```
DEBUG: Searching for CODEOWNERS file (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
DEBUG: Found CODEOWNERS file: * @cmathieu
        (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
DEBUG: No matching CODEOWNERS rule found (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
DEBUG: Created Merge Request #16 (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
```

I also tried with a newline at the end of file, same result.

The branch created by renovate updated a POM file which should match `*`:

```
git diff --stat origin/renovate/xxx-0.x~1
 pom.xml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

There is even a test in lib/workers/pr/code-owners.spec.ts for that:

```typescript
   it('returns global code owner', async () => {
      fs.readLocalFile.mockResolvedValueOnce(['* @jimmy'].join('\n'));
      git.getBranchFiles.mockResolvedValueOnce(['README.md']);
      const codeOwners = await codeOwnersForPr(pr);
      expect(codeOwners).toEqual(['@jimmy']);
    });
```

:thinking:

**Comment by rarkins** [comment]
I've added another log to be included in the next release, it will list the files and rules that are compared.

**Comment by cykl** [comment]
Upgraded to 23.44-slim

```
 INFO: PR created (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
       "pr": 18,
       "prTitle": "Update dependency xxx to v0.0.33"
DEBUG: Searching for CODEOWNERS file (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
DEBUG: Found CODEOWNERS file: * @cmathieu
        (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
DEBUG: PR files and rules to match for CODEOWNERS (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
       "prFiles": null,
       "rules": [{"usernames": ["@cmathieu"]}]
DEBUG: No matching CODEOWNERS rule found (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
```

Any idea why prFile would be null? If it helps, here is my full config (no repository side configuration):

```json
 config: |
    {
      "dryRun": false,
      "printConfig": true,
      "logLevel": "debug",

      "platform": "gitlab",
      "endpoint": "xxx",
      "author": "xxx",
      "assigneesFromCodeOwners": true,
      "assigneesSampleSize": 1,
      "labels": [
        "type::maintenance"
      ],

      "prConcurrentLimit": 3,
      "prCreation": "immediate",
      "prFooter": null,
      "prHourlyLimit": 1,
      "prNotPendingHours": 1,
      "timezone": "Europe/Paris",

      "dependencyDashboard": true,

      "onboarding": false,
      "requireConfig": false,

      "packageRules": [
        {
          "datasources": [
            "maven"
          ],
          "registryUrls": [
            "xxx"
          ]
        }
      ],
      "hostRules": [
        xxx
      ],

      "java": {},

      "repositories": [
        "backend/pilot-java-api"
      ]
    }
```

**Comment by cykl** [comment]
I'm not a typescript / node developer, but if you can give me some simple instructions to connect a debugger to the process running into the container, I can dig into it.

**Comment by rarkins** [comment]
Seems there's an error when running `git.diffSummary()` to get the list of files. I've added *another* extra log for that now, so I suggest trying that once it's released. Are you doing anything "interesting" with the way you use git with Renovate?

**Comment by cykl** [comment]
None I'm aware of. This is a very simple test project. Its history is as simple as:

```
* a16ca36 - (origin/renovate/xxx-0.x) Update dependency xxx to v0.0.33 (6 hours ago) <renovatebot>
* adbd621 - (HEAD -> master, origin/master, origin/HEAD) Revert "Add newline at the end of CODEOWNERS" (6 hours ago) <Clément MATHIEU>
* 4e8daf3 - Add newline at the end of CODEOWNERS (8 hours ago) <Clément MATHIEU>
* f9eb8e2 - Add CODEOWNERS (2 days ago) <Clément MATHIEU>
* fab6f96 - Downgrade xxx to 0.0.32 (test drive renovatebot) (3 days ago) <Clément MATHIEU>
| * da38ca9 - (origin/poc_xxx) xxx (6 days ago) <Clément MATHIEU>
|/  
* 7954fb3 - xxx (2 weeks ago) <Clément MATHIEU>
* df99ca9 - xxx (2 weeks ago) <Clément MATHIEU>
* 07b2fe7 - xxx (2 weeks ago) <Clément MATHIEU>
* 1aac8fa - xxx (2 weeks ago) <Clément MATHIEU>
* 2a6aeeb - xxx (2 weeks ago) <Clément MATHIEU>
* 16bc260 - Bootstrap project (2 weeks ago) <Clément MATHIEU>
```

I will upgrade to next release. If logs still don't help us, I will try using another newly created repository.

**Comment by rarkins** [comment]
We only do a shallow clone with depth 2, but I can't think why that would cause a problem. Hopefully the new logging sheds some light.

**Comment by cykl** [comment]
```
WARN: getBranchFiles error (repository=backend/pilot-java-api, branch=renovate/xxx-0.x)
       "err": {
         "task": {
           "concatStdErr": false,
           "format": "utf-8",
           "commands": [
             "diff",
             "--stat=4096",
             "renovate/xxx-0.x",
             "master"
           ]
         },
         "message": "fatal: ambiguous argument 'renovate/xxx-0.x': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: fatal: ambiguous argument 'renovate/xxx-0.x': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:66:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:58:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
```

I might try to reverse engineer the git command sequence from the log. Is there an easier way to observe cloned repository state and executed commands?

**Comment by rarkins** [comment]
If you run from source ("yarn start ... ") and add a process.exit() after the diff warning then renovate will exit immediately and leave the git state as-is. It should be somewhere under /tmp/renovate/ (exact path would be in the early logs).

**Comment by cykl** [comment]
```
DEBUG: Added assignees (repository=backend/pilot-java-api, branch=renovate/xxxx-0.x)
       "assignees": ["cmathieu"]
```

This is interesting. If I delete both the renovate branch and the MR then is MR is assigned to me. If I only delete the MR then MR is unassigned. Git commands sequence likely differs when branch already exists and remote refs are not properly configured.

However, I am fairly confident that I removed the renovate branch (and even the dashboard issue) several times but never observed that MR was assigned to me :thinking:

**Comment by rarkins** [comment]
Can you reproduce the same now? Rename then close the MR, but leave the branch. Then run again

**Comment by cykl** [comment]
Yes, this seems deterministic. Let's assume this is the root cause and that I did something won't during my early tests.

**Comment by cykl** [comment]
I think I just figured it out. My previous config was using prCreation = not-pending rather than immediate. In not-pending mode, renovate branch already exists when MR is created.

**Comment by rarkins** [comment]
@cykl can you reproduce that if prCreation=not-pending then assigning from CODEOWNERS doesn't happen when the MR is created?

**Comment by bydga** [comment]
Hi, i encounterer this err too - having codeowners, prCreation=not-pending and noone gets assigned. :/ 
In the log i can see this (in the second run after pipelines passed): 
```DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 0 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: processBranch with 1 upgrades (repository=hera/example-api, dependencies=redis, branch=renovate/redis-3.x)
DEBUG: Setting current branch to master (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: latest commit (repository=hera/example-api, branch=renovate/redis-3.x)
       "branchName": "master",
       "latestCommitDate": "2020-10-12T09:20:52+00:00"
DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 0 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: branchExists=true (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Branch has 1 upgrade(s) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: recreateClosed is false (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: findPr(renovate/redis-3.x, Update dependency redis to v3, !open) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: prAlreadyExisted=false (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Checking if PR has been edited (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Checking schedule(at any time, null) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: No schedule defined (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Branch already exists (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 0 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Branch does not need rebasing (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Using reuseExistingBranch: true (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: manager.getUpdatedPackageFiles() (repository=hera/example-api, branch=renovate/redis-3.x)
       "reuseExistingBranch": true,
       "branchName": "renovate/redis-3.x"
DEBUG: npm.updateDependency(): dependencies.redis = ^3.0.2 (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: No package files need updating (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Getting updated lock files (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: lock file dirs (repository=hera/example-api, branch=renovate/redis-3.x)
       "dirs": {
         "yarnLockDirs": [],
         "npmLockDirs": [],
         "pnpmShrinkwrapDirs": [],
         "lernaDirs": []
       }
DEBUG: Writing repo .npmrc (/tmp/renovate/repos/gitlab/hera/example-api) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Writing package.json files (repository=hera/example-api, branch=renovate/redis-3.x)
       "packageFiles": ["package.json"]
DEBUG: Writing package-lock.json (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Writing any updated package files (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: No updated lock files in branch (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: No files to commit (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 2 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Status check renovate/stability-days is already up-to-date (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Checking if we can automerge branch (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: mergeStatus=no automerge (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Ensuring PR (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: There are 0 errors and 0 warnings (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 0 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Checking branch combined status (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: getBranchStatus(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 2 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: getBranchStatus() result (repository=hera/example-api, branch=renovate/redis-3.x)
       "branchStatus": "green",
       "branchName": "renovate/redis-3.x"
DEBUG: Branch status success (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Creating PR (repository=hera/example-api, branch=renovate/redis-3.x)
       "prTitle": "Update dependency redis to v3"
DEBUG: Creating Merge Request: Update dependency redis to v3 (repository=hera/example-api, branch=renovate/redis-3.x)
 INFO: PR created (repository=hera/example-api, branch=renovate/redis-3.x)
       "pr": 354,
       "prTitle": "Update dependency redis to v3"
DEBUG: Searching for CODEOWNERS file (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Found CODEOWNERS file: * @bydzovskym @anotheruser
        (repository=hera/example-api, branch=renovate/redis-3.x)
 WARN: getBranchFiles error (repository=hera/example-api, branch=renovate/redis-3.x)
       "err": {
         "task": {
           "concatStdErr": false,
           "format": "utf-8",
           "commands": ["diff", "--stat=4096", "renovate/redis-3.x", "master"]
         },
         "message": "fatal: ambiguous argument 'renovate/redis-3.x': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: fatal: ambiguous argument 'renovate/redis-3.x': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at GitExecutorChain.onFatalException (/Users/bydga/.nvm/versions/node/v12.13.0/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/Users/bydga/.nvm/versions/node/v12.13.0/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/Users/bydga/.nvm/versions/node/v12.13.0/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
DEBUG: PR files and rules to match for CODEOWNERS (repository=hera/example-api, branch=renovate/redis-3.x)
       "prFiles": null,
       "rules": [{"usernames": ["@bydzovskym", "@anotheruser"]}]
DEBUG: No matching CODEOWNERS rule found (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Created Merge Request #354 (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Checking #354 for automerge (repository=hera/example-api, branch=renovate/redis-3.x)
       "automerge": false,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 0 results (repository=hera/example-api, branch=renovate/redis-3.x)
```




The `ambiguous argument 'renovate/redis-3.x': unknown revision or path not in the working tree` is weird - when I change the prCreation=immediate, everything works as expected - the log in such case is: 



```
DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: processBranch with 1 upgrades (repository=hera/example-api, dependencies=redis, branch=renovate/redis-3.x)
DEBUG: Setting current branch to master (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: latest commit (repository=hera/example-api, branch=renovate/redis-3.x)
       "branchName": "master",
       "latestCommitDate": "2020-10-12T10:31:48+00:00"
DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: branchExists=false (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Branch has 1 upgrade(s) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: recreateClosed is false (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: findPr(renovate/redis-3.x, Update dependency redis to v3, !open) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: prAlreadyExisted=false (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Checking schedule(at any time, null) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: No schedule defined (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Branch needs creating (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Using reuseExistingBranch: false (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: manager.getUpdatedPackageFiles() (repository=hera/example-api, branch=renovate/redis-3.x)
       "reuseExistingBranch": false,
       "branchName": "renovate/redis-3.x"
DEBUG: npm.updateDependency(): dependencies.redis = ^3.0.2 (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Updating packageFile content (repository=hera/example-api, packageFile=package.json, branch=renovate/redis-3.x)
       "depName": "redis"
DEBUG: Updated 1 package files (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Getting updated lock files (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: lock file dirs (repository=hera/example-api, branch=renovate/redis-3.x)
       "dirs": {
         "yarnLockDirs": [],
         "npmLockDirs": ["package-lock.json"],
         "pnpmShrinkwrapDirs": [],
         "lernaDirs": []
       }
DEBUG: Writing repo .npmrc (/tmp/renovate/repos/gitlab/hera/example-api) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Writing package.json files (repository=hera/example-api, branch=renovate/redis-3.x)
       "packageFiles": ["package.json"]
DEBUG: Writing package-lock.json (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Writing any updated package files (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Writing package.json (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: npmrc file found in repository (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Generating package-lock.json for . (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Spawning npm install to create /tmp/renovate/repos/gitlab/hera/example-api/package-lock.json (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Updating lock file only (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Using node constraint "12" from package.json (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Executing command (repository=hera/example-api, branch=renovate/redis-3.x)
       "command": "npm install --package-lock-only --ignore-scripts --no-audit"
DEBUG: exec completed (repository=hera/example-api, branch=renovate/redis-3.x)
       "cmd": "npm install --package-lock-only --ignore-scripts --no-audit",
       "durationMs": 1570,
       "stdout": "added 696 packages in 1.145s\n",
       "stderr": ""
DEBUG: package-lock.json needs updating (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Updated 1 lock files (repository=hera/example-api, branch=renovate/redis-3.x)
       "updatedArtifacts": ["package-lock.json"]
DEBUG: 2 file(s) to commit (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Committing files to branch renovate/redis-3.x (repository=hera/example-api, branch=renovate/redis-3.x)
 INFO: Branch created (repository=hera/example-api, branch=renovate/redis-3.x)
       "commitSha": "124a1f1"
DEBUG: Got res with 1 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Updating renovate/stability-days status check state to green (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Ensuring PR (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: There are 0 errors and 0 warnings (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: getBranchPr(renovate/redis-3.x) (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Got res with 0 results (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Creating PR (repository=hera/example-api, branch=renovate/redis-3.x)
       "prTitle": "Update dependency redis to v3"
DEBUG: Creating Merge Request: Update dependency redis to v3 (repository=hera/example-api, branch=renovate/redis-3.x)
 INFO: PR created (repository=hera/example-api, branch=renovate/redis-3.x)
       "pr": 374,
       "prTitle": "Update dependency redis to v3"
DEBUG: Searching for CODEOWNERS file (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Found CODEOWNERS file: * @bydzovskym @anotheruser
        (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: PR files and rules to match for CODEOWNERS (repository=hera/example-api, branch=renovate/redis-3.x)
       "prFiles": ["package-lock.json", "package.json"],
       "rules": [{"usernames": ["@bydzovskym", "@anotheruser"]}]
DEBUG: CODEOWNERS matched the following usernames: ["@bydzovskym","@anotheruser"] (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Adding assignees 'bydzovskym, anotheruser' to #374 (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Added assignees (repository=hera/example-api, branch=renovate/redis-3.x)
       "assignees": ["bydzovskym", "anotheruser"]
DEBUG: Created Merge Request #374 (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Ensuring comment "⚠️ Artifact update problem" in #374 is removed (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Getting comments for #374 (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Found 2 comments (repository=hera/example-api, branch=renovate/redis-3.x)
DEBUG: Checking #374 for automerge (repository=hera/example-api, branch=renovate/redis-3.x)
       "automerge": false,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=hera/example-api, branch=renovate/redis-3.x)
```
