### ISSUE TITLE
A pull request already exists to configure renovate

### ISSUE THREAD

**Issue by agaudreault-jive** [renovatebot/config-help#908]
**What Renovate type, platform and version are you using?**

Using self hosted renovate version `23.41.0` with github.

**Describe the bug**

When a pull request to configure renovate is open, it tries to re-create it and the github error is returned. It should check if a PR already exist before.

**Relevant debug logs**

```
  WARN: Host error (repository=octopus/my-repository)
        "hostType": "github",
        "lookupName": undefined,
        "err": {
          "name": "HTTPError",
          "timings": {
            "start": 1602017038953,
            "socket": 1602017038953,
            "lookup": 1602017039004,
            "connect": 1602017039081,
            "secureConnect": 1602017039160,
            "upload": 1602017039160,
            "response": 1602017039584,
            "end": 1602017039584,
            "phases": {
              "wait": 0,
              "dns": 51,
              "tcp": 77,
              "tls": 79,
              "request": 0,
              "firstByte": 424,
              "download": 0,
              "total": 631
            }
          },
          "message": "Response code 422 (Unprocessable Entity)",
          "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
          "options": {
            "headers": {
              "user-agent": "https://github.com/renovatebot/renovate",
              "accept-encoding": "gzip, deflate",
              "accept": "application/vnd.github.v3+json",
              "authorization": "***********",
              "content-type": "application/json",
              "content-length": "4281"
            },
            "url": "https://api.github.com/repos/octopus/my-repository/pulls",
            "username": "",
            "password": "***********",
            "method": "POST",
            "http2": false
          },
          "response": {
            "statusCode": 422,
            "statusMessage": "Unprocessable Entity",
            "body": {
              "message": "Validation Failed",
              "errors": [
                {
                  "resource": "PullRequest",
                  "code": "custom",
                  "message": "A pull request already exists for octopus:renovate/configure."
                }
              ],
              "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
            },
            "headers": {
              "server": "GitHub.com",
              "date": "Tue, 06 Oct 2020 20:43:59 GMT",
              "content-type": "application/json; charset=utf-8",
              "content-length": "245",
              "connection": "close",
              "status": "422 Unprocessable Entity",
              "x-oauth-scopes": "repo, user",
              "x-accepted-oauth-scopes": "",
              "x-github-media-type": "github.v3; format=json",
              "x-ratelimit-limit": "5000",
              "x-ratelimit-remaining": "4859",
              "x-ratelimit-reset": "1602020388",
              "x-ratelimit-used": "141",
              "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
              "access-control-allow-origin": "*",
              "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
              "x-frame-options": "deny",
              "x-content-type-options": "nosniff",
              "x-xss-protection": "1; mode=block",
              "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
              "content-security-policy": "default-src 'none'",
              "vary": "Accept-Encoding, Accept, X-Requested-With",
              "x-github-request-id": "615E:53C1:D6C97:1589A4:ABCDABCD"
            },
            "httpVersion": "1.1"
          }
        }
  INFO: External host error causing abort - skipping (repository=octopus/my-repository)
```

**To Reproduce**

Run twice for a new repository.

**Additional context**

**Comment by rarkins** [comment]
Renovate does check for existing of PR. You should see a log like the following:

```
DEBUG: findPr(renovate/configure, Configure Renovate, !open) (repository=renovate-tests/onboarding7)
DEBUG: Retrieving PR list (repository=renovate-tests/onboarding7)
DEBUG: Retrieved 1 Pull Requests (repository=renovate-tests/onboarding7)
DEBUG: Found no closed onboarding PR (repository=renovate-tests/onboarding7)
DEBUG: Repo is not onboarded (repository=renovate-tests/onboarding7)
DEBUG: getBranchPr(renovate/configure) (repository=renovate-tests/onboarding7)
DEBUG: findPr(renovate/configure, undefined, open) (repository=renovate-tests/onboarding7)
DEBUG: Found PR #1 (repository=renovate-tests/onboarding7)
DEBUG: Returning from graphql open PR list (repository=renovate-tests/onboarding7)
DEBUG: Onboarding PR already exists (repository=renovate-tests/onboarding7)
```

Please compare to your own (debug) log. Also suggested:
- Are you running the latest version?
- Do you have any custom bot config?
- Can you reproduce the problem in a public repo?

**Comment by agaudreault-jive** [comment]
Here is the relevant debug logs for this repo. I can't help but notice the `undefined` in the `findPr` log. I am running docker version `23.41.0`

```
DEBUG: Returning 4 branch(es) (repository=octopus/my-repository)
DEBUG: config.repoIsOnboarded=false (repository=octopus/my-repository)
DEBUG: ensureOnboardingPr() (repository=octopus/my-repository)
DEBUG: getBranchPr(renovate/configure) (repository=octopus/my-repository)
DEBUG: findPr(renovate/configure, undefined, open) (repository=octopus/my-repository)
DEBUG: Filling in onboarding PR template (repository=octopus/my-repository)
DEBUG: getConfigDesc() (repository=octopus/my-repository)
DEBUG: getDescriptionArray() (repository=octopus/my-repository)
DEBUG: getScheduleDesc() (repository=octopus/my-repository)
DEBUG: No schedule (repository=octopus/my-repository)
DEBUG: Found description array (repository=octopus/my-repository)
       "length": 13
DEBUG: getPrList() (repository=octopus/my-repository)
DEBUG: Creating onboarding PR (repository=octopus/my-repository)
DEBUG: Creating PR (repository=octopus/my-repository)
       "title": "Configure Renovate",
       "head": "jive:renovate/configure",
       "base": "master",
       "draft": false
DEBUG: 422 Error thrown from GitHub (repository=octopus/my-repository)
```

The branch exist
![image](https://user-images.githubusercontent.com/47184027/95339128-b9722100-0881-11eb-8a5d-36d038708427.png).

While investigating more, it seems like the PR was created with our old renovate user defined in `RENOVATE_LEGACY_GIT_AUTHOR_EMAIL`. The new user is still updating the PR and force pushing, but that might be the problem.

I will try to Edit the title, close the PR and delete the branch, to see what happens.

**Comment by rarkins** [comment]
Yes, if you have changed the *account* which Renovate is run as then it won't detect PRs created by different accounts The legacy author email is used only later when it comes to identifying who made the commits, not who created the PR. If you do as you suggest and rename then delete, I'd expect it to work again.

**Comment by agaudreault-jive** [comment]
That was it! Thank you :)
