### ISSUE TITLE
Renovate Error

### ISSUE THREAD

**Issue by Rahul-learn** [renovatebot/config-help#915]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We are seeing below error message for one of our repository. Could you please let me know I am missing anything?

at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:66:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:58:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97

**Comment by viceice** [comment]
You need to provide a lot more information. With this little we can't help you.
