### ISSUE TITLE
Repository has changed during renovation - aborting

### ISSUE THREAD

**Issue by Shub1nk** [renovatebot/config-help#924]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

**Gitlab CI/CD job renovate**

```
Created fresh repository.
Checking out d9cb4f39 as develop...
Skipping Git submodules setup
Executing "step_script" stage of the job script
01:43
$ cp tools/renovate/config.js config.js
$ ln -sF $CI_PROJECT_DIR/config.js /usr/src/app/
$ node /usr/src/app/dist/renovate.js
 INFO: Repository started (repository=company/nodejs/assr)
       "renovateVersion": "19.239.11"
 INFO: Dependency extraction complete (repository=company/nodejs/assr)
       "baseBranch": "develop",
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 1, "depCount": 1},
           "gitlabci": {"fileCount": 1, "depCount": 23},
           "helm-values": {"fileCount": 1, "depCount": 1},
           "npm": {"fileCount": 7, "depCount": 342},
           "nvm": {"fileCount": 1, "depCount": 1}
         },
         "total": {"fileCount": 11, "depCount": 368}
       }
 INFO: Repository has changed during renovation - aborting (repository=company/nodejs/assr)
 INFO: Repository finished (repository=company/nodejs/assr)
       "durationMs": 100639
```
------

**In PR problem log**

Artifact problem update

File name: yarn.lock

....
error An unexpected error occurred: "https://registry.yarnpkg.com/@company/styles/-/styles-1.1.0.tgz: Request failed \"404 Not Found\"".

------

**config.js**
```
module.exports = {
    platform: 'gitlab',
    endpoint: 'http://gitlab-endpoint-company/api/v4/',
    assignees: ['gitlab-bot'],
    baseBranches: ['develop'],
    rebaseWhen: 'auto',
    semanticCommits: true,
    labels: [RENOVATE],
    logLevel: 'debug',
    packageRules: [
        {
            packagePatterns: ['^@company'],
            enabled: false
        }
    ],
    minor: {
        labels: [RENOVATE, 'minor']
    },
    major: {
        labels: [RENOVATE, 'major']
    },
    repositories: ['company/nodejs/assr'],
    extends: ['config:base', ':pinAllExceptPeerDependencies'],
};
```
------

**.npmrc**

```
//registry.npmjs.org/:_authToken=${COMPANY_NPM_TOKEN}
tag-version-prefix="v"
message="feat: bump version to %s :tada:"
sign-git-commit=false
sign-git-tag=false
save-exact=true
```

### What would you like to do?

RenovateBot launched, created 2 PRs, but cannot update artifacts because yarn is launched with a flag `--frozen-lockfile`.

I noticed that after the launch of the renovate, an additional stage of the renovate/artifacts is started. It ends with an error.

It turns out that in PR `package.json` is being updated and the `yarn.lock` file cannot be updated, either because there is a flag of `--frozen-lockfile` or there are private modules.

**Comment by rarkins** [comment]
Please edit so that any code or logs use three ` symbols as described in https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

It will then be easier to read and understand what you've written.

Please also ensure that you are capturing logs at debug level, e.g. LOG_LEVEL=debug in env.

**Comment by Shub1nk** [comment]
`logLevel: 'debug'` log-level debug is set to `config.js`

**Comment by rarkins** [comment]
> `logLevel: 'debug'` is set to `config.js`

There are no `DEBUG:` messages in your log here, which indicates that this config file is not being read. Please try to troubleshoot that aspect first as it may explain your subsequent problems. Otherwise, please use our officially built `npm` package or Docker image and try again.

**Comment by Shub1nk** [comment]
`DEBUG` works. It's just 9k lines. I didn’t use it

There are 2 problems:

problem 1

```
DEBUG: Error commiting files (repository=company/nodejs/assr, branch=company/loadable-babel-plugin-5.x)
remote: GitLab: Branch name does not follow the pattern 'master|develop|revert*|release\\/\\d+\\.\\d+|(feature|hotfix|bugfix|renovate)\\/.{8,24}$'
```

`loadable-babel-plugin-5.x` = 25 symbols

I corrected it

problem 2

```
DEBUG: lock file error (repository=company/nodejs/assr, branch=renovate/loadable-babel-plugin-5.x)
       "cmd": "node /usr/local/node-v12.16.3-linux-x64/lib/node_modules/yarn/bin/yarn.js",
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "node /usr/local/node-v12.16.3-linux-x64/lib/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform",
         "stdout": "yarn install v1.22.4\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo If you think this is a bug, please open a bug report with the information provided in \"/tmp/renovate/repos/gitlab/company/nodejs/assr/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
         "stderr": "warning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.4\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^2.0.4\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.1.0\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.0.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.6\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.16\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.4\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.0.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.17\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.5\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^2.0.1\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.21\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^2.0.3\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.22\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.21\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.22\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^1.0.25\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.13\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/query-params-provider@4.0.5\" is incompatible with requested version \"@company/query-params-provider@^2.0.22\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/query-params-provider@4.0.5\" is incompatible with requested version \"@company/query-params-provider@^6.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.3\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.3\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.6\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nerror An unexpected error occurred: \"https://**redacted**@company/util-create-widget/-/util-create-widget-2.0.39.tgz: Request failed \\\"404 Not Found\\\"\".\n",
         "message": "Command failed: node /usr/local/node-v12.16.3-linux-x64/lib/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.4\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^2.0.4\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.1.0\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.0.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.6\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.16\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.4\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.0.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.17\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.5\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^2.0.1\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.21\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^2.0.3\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.22\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.21\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.22\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^1.0.25\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.13\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/query-params-provider@4.0.5\" is incompatible with requested version \"@company/query-params-provider@^2.0.22\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/query-params-provider@4.0.5\" is incompatible with requested version \"@company/query-params-provider@^6.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.3\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.3\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.6\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nerror An unexpected error occurred: \"https://**redacted**@company/util-create-widget/-/util-create-widget-2.0.39.tgz: Request failed \\\"404 Not Found\\\"\".\n",
         "stack": "Error: Command failed: node /usr/local/node-v12.16.3-linux-x64/lib/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.4\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^2.0.4\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.1.0\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.0.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.6\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.16\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.4\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.0.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.17\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.5\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^2.0.1\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.21\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^2.0.3\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.22\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.21\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^2.1.22\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^1.0.25\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/geo-info@1.0.11\" is incompatible with requested version \"@company/geo-info@^3.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.5\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^1.3.13\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/query-params-provider@4.0.5\" is incompatible with requested version \"@company/query-params-provider@^2.0.22\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^5.1.0\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.7\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^5.1.0\"\nwarning Resolution field \"@company/query-params-provider@4.0.5\" is incompatible with requested version \"@company/query-params-provider@^6.1.0\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^4.0.3\"\nwarning Resolution field \"@company/popover@1.3.12\" is incompatible with requested version \"@company/popover@^3.0.3\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.6\"\nwarning Resolution field \"@company/event-bus@2.1.16\" is incompatible with requested version \"@company/event-bus@^3.0.7\"\nerror An unexpected error occurred: \"https://**redacted**@company/util-create-widget/-/util-create-widget-2.0.39.tgz: Request failed \\\"404 Not Found\\\"\".\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:310:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)"
       },
       "stdout": "",
       "stderr": "",
       "type": "yarn"
DEBUG: No updated lock files in branch (repository=company/nodejs/assr, branch=renovate/loadable-babel-plugin-5.x)
```
I add in `config.js`
```
    encrypted: {
        npmToken:
            'cMyx6YMwcFCOT4wUm7t5gRswjhX3u3YWq846PbU2O4cydxsj9gcvNZ2sUWRtyRGjjswqIquGWEIVT6e4WjF5WTC5+o1GfJQWmUygGtUm0Z27jeBsymUQg0jmmtn9DjzvIR/tknKDdYnr8YWB3kYtAPsG6FAoXZBluEc0MdXYDxjSJ8T7D3FGzWkk04yZpffMeAg4fusQGm/kynlCbJHebDYnVT/OYnJ+IYEScaqg6NdC8ipMiAgkF69VGUq9G4j3kFBbeXY9fVUWxd1QZJlGvU/D6zvf2ULD3iS45zs3INDAKkf1lUly9d37jOw5FQNQT04W23TXdJo4DwbCYPLEug==',
        npmrc:
            'IPFYIPX5bxQJTSxFJV4u6kEe40iJS+sWSguJN1OygMJbrAtMiLiyeC4L+38VOP42uxc1qzBLjDJ8ZhIoRL1BE2daRGM7f4NwSKy8w/JMyOvQ+UuZao2b0nwXh3IY/k721vFvue1dEEWhMIsLZtk+zw1cDgxSWFhLNc1iZn/81LuTNlLO0M2cXEiRZQ2mLcrIIcq4KwPv99A85rR3Xl85+pPDMFBiXhHLOphEW6qEoJ4PxB2n4qFVeQBDJxuUQrnCWL8CGnkMbLIcUr4XTi5Dxw6FIDCBm0MwU5yzDF8BSf7rdGtHpBzHgTO8fn9JXWyFLx3oilhrSk2OrsKMN29Ztw=='
    }
```

And I still get an update error `yarn.lock`

**Comment by rarkins** [comment]
Completely remove the `encrypted` object from your `config.js` and replace it instead with an unencrypted `npmrc` field that includes any necessary tokens within instead of via env. I think you should only need the first line of your `.npmrc` too - the rest are not used by Renovate.

**Comment by Shub1nk** [comment]
Cool! It all worked.

Is it possible to `.npmrs` or at least hide the token? The repository, although private, is not cool when the token is stored in the open form

**Comment by rarkins** [comment]
If you set the same string as `RENOVATE_NPMRC` then it should work the same way as putting it in the `config.js`. Replace newlines with `\n` string literals before exporting it to env.

**Comment by Shub1nk** [comment]
Okay. Thanks for helping
