### ISSUE TITLE
Struggling with a self-hosted instance pulling from Artifactory

### ISSUE THREAD

**Issue by mikeycmccarthy** [renovatebot/config-help#929]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

We've checked them, the only potentially relevant line seems to be ones matching this format, calling out to GitHub itself:

```
-10-17T21:32:14.497859000Z          "message": "Invalid character in header content [\"authorization\"]",
2020-10-17T21:32:14.498071000Z          "stack": "RequestError: Invalid character in header content [\"authorization\"]\n    at get (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:236:15)\n    at Immediate.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:305:10)"
2020-10-17T21:32:14.498265000Z        }
2020-10-17T21:34:56.677457000Z  INFO: getReleaseList error (repository=acdlite/recompose)
2020-10-17T21:34:56.683706000Z        "err": {
2020-10-17T21:34:56.683949000Z          "name": "RequestError",
2020-10-17T21:34:56.684159000Z          "code": "ERR_INVALID_CHAR",
2020-10-17T21:34:56.684417000Z          "hostname": "api.github.com",
2020-10-17T21:34:56.684635000Z          "method": "GET",
```

### What would you like to do?

We're trying to run the WhiteSource Renovate app as a container on-premise, for projects that use both private and public NPM modules, but all accessed through an on-premise registry (Artifactory), which presents both private and public packages as a single repository (a 'virtual' repository) in Artifactory terms. We've been following the guides at https://docs.renovatebot.com/private-modules/.

'Commit .npmrc file into repository' -> this won't work for us unfortunately, we consider the content of this file sensitive and don't want it in git.

'If you are running your own Renovate bot: copy an .npmrc file to the home dir of the bot and it will work for all repositories' -> this does seem to work, but as each team has their own repos this may mean needing to run multiple bots.

'Add an encrypted npm token to Renovate config' -> the access token received back from Artifactory after an npm login is huge - much bigger in our case than the size of a typical npmrc without the token, so the encryption tool does not work on this.

'Encrypted entire .npmrc file into config' -> This is what we think seems the best solution, and the string does encrypt, but Renovate only seems to want to go to yarnpkg for packages and we can't seem to get it to update private ones. The string we're encrypting looks like this:

```
"npmrc": "registry=https://artifactory.XXX.co.uk/artifactory/api/npm/OUR_PRIVATE_REPO/\n_auth= ZZZZZZZZZZZZZ\nemail=YYY@XXX.co.uk\nalways-auth=true\n"
```

(Obviously XXX and YYY ZZZ and OUR_PRIVATE_REPO have just been put in to keep this private). 

The _auth is what we see in our npmrc files and can pull private packages with (based on the setup described at https://www.jfrog.com/confluence/display/JFROG/npm+Registry ('Authenticating the npm Client'). Artifactory is not happy wthout the always-auth and the email so they have to go in there.

As well as struggling with this, there's also a more general question in the Artifactory is a pull through cache when proxying remote repos - you don't 'see' the latest version in Artifactory unless someone has pulled it and it hasn't expired from cache since that point. Do you know how Renovate deals with this?

Many many thanks in advance for any help anyone can give here.

**Comment by rarkins** [comment]
When you're self-hosting, you don't/shouldn't *encrypt*. e.g. the `npmrc` string in your `config.js` should be the regular `.npmrc` content and not modified.

It seems like there's more to the error `"RequestError: Invalid character in header content [\"authorization\"]`. Is that a rejection from Artifactory?

> As well as struggling with this, there's also a more general question in the Artifactory is a pull through cache when proxying remote repos - you don't 'see' the latest version in Artifactory unless someone has pulled it and it hasn't expired from cache since that point. Do you know how Renovate deals with this?

I'm not a fan of Artifactory for these types of reasons. Surprisingly nobody has mentioned this before though and we do have a lot of Artifactory users. Are you sure that the JSON registry result isn't proxied through even if the tarballs don't exist yet? Unfortunately I'm not aware of how to deal with a mandatory registry that returns wrong results if it's like you describe.

**Comment by mikeycmccarthy** [comment]
Thanks @rarkins  - I must have missed the bit about not encrypting for self-hosted, my apologies. It seems the custom npmrc in the bot might be the best approach.

I will confirm the Artifactory behaviour - I believe I have see it resolve the latest versions via Artifactory even when they weren't visible there so maybe it's as you said, some additional metadata between npmjs and Artifactory that lets Artifactory know there are later versions than what it holds.

The log related to the rejection is in the Renovate bot logs, here's the full thing:

```
2020-10-18T20:09:51.010693000Z  INFO: getReleaseList error (repository=babel/babel)
2020-10-18T20:09:51.011045000Z        "err": {
2020-10-18T20:09:51.011308000Z          "name": "RequestError",
2020-10-18T20:09:51.011577000Z          "code": "ERR_INVALID_CHAR",
2020-10-18T20:09:51.011822000Z          "hostname": "api.github.com",
2020-10-18T20:09:51.012077000Z          "method": "GET",
2020-10-18T20:09:51.012327000Z          "path": "/repos/babel/babel/releases?per_page=100",
2020-10-18T20:09:51.012588000Z          "protocol": "https:",
2020-10-18T20:09:51.012829000Z          "url": "https://api.github.com/repos/babel/babel/releases?per_page=100",
2020-10-18T20:09:51.013067000Z          "gotOptions": {
2020-10-18T20:09:51.013315000Z            "path": "/repos/babel/babel/releases?per_page=100",
2020-10-18T20:09:51.013572000Z            "protocol": "https:",
2020-10-18T20:09:51.013812000Z            "hostname": "api.github.com",
2020-10-18T20:09:51.014106000Z            "hash": "",
2020-10-18T20:09:51.014348000Z            "search": "?per_page=100",
2020-10-18T20:09:51.016017000Z            "pathname": "/repos/babel/babel/releases",
2020-10-18T20:09:51.016314000Z            "href": "https://api.github.com/repos/babel/babel/releases?per_page=100",
2020-10-18T20:09:51.016605000Z            "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
2020-10-18T20:09:51.016862000Z            "headers": {
2020-10-18T20:09:51.017119000Z              "user-agent": "WhiteSource Renovate",
2020-10-18T20:09:51.017362000Z              "accept": "application/vnd.github.machine-man-preview+json",
2020-10-18T20:09:51.018634000Z              "accept-encoding": "gzip, deflate",
2020-10-18T20:09:51.018922000Z              "authorization": "***********"
2020-10-18T20:09:51.019169000Z            },
2020-10-18T20:09:51.019505000Z            "hooks": {
2020-10-18T20:09:51.019751000Z              "beforeError": [],
2020-10-18T20:09:51.020001000Z              "init": [],
2020-10-18T20:09:51.020241000Z              "beforeRequest": [],
2020-10-18T20:09:51.021966000Z              "beforeRedirect": [null],
2020-10-18T20:09:51.022271000Z              "beforeRetry": [],
2020-10-18T20:09:51.022544000Z              "afterResponse": []
2020-10-18T20:09:51.028150000Z            },
2020-10-18T20:09:51.028451000Z            "decompress": true,
2020-10-18T20:09:51.028745000Z            "throwHttpErrors": true,
2020-10-18T20:09:51.028998000Z            "followRedirect": true,
2020-10-18T20:09:51.029239000Z            "stream": false,
2020-10-18T20:09:51.029501000Z            "form": false,
2020-10-18T20:09:51.029742000Z            "json": true,
2020-10-18T20:09:51.029980000Z            "cache": false,
2020-10-18T20:09:51.030217000Z            "useElectronNet": false,
2020-10-18T20:09:51.031744000Z            "method": "GET",
2020-10-18T20:09:51.032000000Z            "hostType": "github",
2020-10-18T20:09:51.037379000Z            "baseUrl": "https://github.gamesys.co.uk/api/v3/",
2020-10-18T20:09:51.039799000Z            "gotTimeout": {"request": 60000}
2020-10-18T20:09:51.041078000Z          },
2020-10-18T20:09:51.041363000Z          "message": "Invalid character in header content [\"authorization\"]",
2020-10-18T20:09:51.041630000Z          "stack": "RequestError: Invalid character in header content [\"authorization\"]\n    at get (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:236:15)\n    at Immediat
e.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:305:10)"
```

These are all over the logs, and the User Agent makes it seem like this is a call from Renovate straight to GitHub about one of those dependencies.

In the case of this repo, Babel isn't a top level dependency, but eslint-import-resolver-babel-module is in package.json under devDependencies - perhaps Babel is transitive in some way from that one?

**Comment by rarkins** [comment]
You're getting an error `Invalid character in header content` for the `authorization` field for api.github.com when fetching release notes. This indicates that the token for github.com is invalid. How are you configuring it and how certain are you that the token is correct?

BTW this error most likely has nothing to do with Artifactory.

> In the case of this repo, Babel isn't a top level dependency, but eslint-import-resolver-babel-module is in package.json under devDependencies - perhaps Babel is transitive in some way from that one?

No. It's not because of transitive dependencies but instead because one or more of your dependencies comes from the babel monorepo and so release notes are fetched from there.
