### ISSUE TITLE
Repository for the renovate configuration

### ISSUE THREAD

**Issue by frbuceta** [renovatebot/config-help#930]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```json
INFO: Repository started
{
  "renovateVersion": "23.51.2"
}
DEBUG: Using localDir: /mnt/renovate/gh/adoitaitsolutions/REPOSITORY
DEBUG: Repository cache is valid
DEBUG: initRepo("adoitaitsolutions/REPOSITORY")
DEBUG: Overriding default GitHub endpoint
{
  "endpoint": "https://api.github.com/"
}
DEBUG: No dangling containers to remove
DEBUG: adoitaitsolutions/REPOSITORY default branch = main
DEBUG: Using personal access token for git init
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: Initializing git repository into /mnt/renovate/gh/adoitaitsolutions/REPOSITORY
DEBUG: git clone completed
{
  "durationMs": 1022
}
DEBUG: latest commit
{
  "latestCommitDate": "2020-10-19T18:14:02+02:00"
}
DEBUG: Setting git author name
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: config file exists
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
DEBUG: Repository config
{
  "fileName": "renovate.json",
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>adoitaitsolutions/renovate-config"
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>adoitaitsolutions/renovate-config"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>adoitaitsolutions/renovate-config"
    ]
  }
}
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/adoitaitsolutions/renovate-config/contents/default.json"
}
DEBUG: Failed to retrieve default.json from repo
{
  "statusCode": 404
}
DEBUG: default.json preset not found - trying renovate.json
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/adoitaitsolutions/renovate-config/contents/renovate.json"
}
DEBUG: Failed to retrieve renovate.json from repo
{
  "statusCode": 404
}
DEBUG: Preset fetch error
{
  "preset": "github>adoitaitsolutions/renovate-config",
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at fetchJSONFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/github/index.js:22:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  }
}
INFO: Throwing preset error
{
  "validationError": "Cannot find preset's package (github>adoitaitsolutions/renovate-config)"
}
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (github>adoitaitsolutions/renovate-config)"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 9 Pull Requests
DEBUG: ensureIssue(Action Required: Fix Renovate Configuration)
DEBUG: Reopening previously closed issue
DEBUG: Patching issue
DEBUG: Issue updated
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {},
  "total": 3985
}
DEBUG: http statistics
{
  "hostStats": [
    "api.github.com, 5 requests, 327ms request average, 0ms queue average"
  ],
  "totalRequests": 5
}
INFO: Repository finished
{
  "durationMs": 3985
}
```

### What would you like to do?

I want to have a repository with the renovate settings for the projects but it doesn't work

**Comment by viceice** [comment]
as you can see in the logs, it you should have a `default.json` in your `adoitaitsolutions/renovate-config` config repo.

That repo only contains a `package.json`, which is not supported with `github>...` presets. So copy the `renovate-config/default" section from `package.json` to a new file `default.json`

**Comment by frbuceta** [comment]
Okay perfect, sorry for the inconvenience and thank you very much

**Comment by viceice** [comment]
PLease close this issue if everything is working as expected
